import { useState } from 'react';
import { ChevronRight, RotateCcw } from 'lucide-react';
import './AmariDescriptionLab.css';
type Turn={q:string;a:string[];ok:number;why:string};
const spine='Private, hands-on guided movement that changes how your body moves and feels.';
const turns:Turn[]=[
 {q:'Build the clearest one-line description.',a:['A new wellness routine','Private, hands-on guided movement that changes how your body moves and feels.','A mobility program you can do alone.'],ok:1,why:'Start literal. It keeps Amari concrete.'},
 {q:'What happens in the room?',a:['A fixed mobility routine you repeat alone.','Garrett guides a precise physical setup while the client moves, breathes, and participates.','Passive treatment while the client relaxes.'],ok:1,why:'Amari is active, individual, and guided.'},
 {q:'“I already go to PT.”',a:['Then Amari will work where PT failed.','You do not have to stop anything helping you. Amari is a different guided experience; come feel it and decide whether it is useful alongside what you do.','PT is not really the same thing.'],ok:1,why:'Respect existing care. Do not compete or argue.'},
 {q:'“Will it help my lower back?”',a:['Yes. It fixes lower-back pain quickly.','Lower-back discomfort can be a reason to come in, but Garrett would need to see what is present. The Assessment lets you experience the work before deciding what comes next.','It is not about pain at all.'],ok:1,why:'Be direct without making a promise.'},
];
export default function AmariDescriptionLab(){const[i,setI]=useState(0),[pick,setPick]=useState<number|null>(null),[checked,setChecked]=useState(false),[miss,setMiss]=useState(0),[speak,setSpeak]=useState(false);const t=turns[i];const last=i===turns.length;const good=last||pick===t.ok;function next(){if(!good)setMiss(miss+1);if(last){setI(0);setPick(null);setChecked(false);setSpeak(false);return;}setI(i+1);setPick(null);setChecked(false)}return <section className="amari-game"><header><span>DESCRIBE AMARI · ROUND 01</span><h2>{last?'Say it aloud: “What is Amari?”':t.q}</h2><div className="amari-game__meter"><i style={{width:`${((i+1)/(turns.length+1))*100}%`}}/><small>{i+1} / {turns.length+1}</small></div></header><main>{last?<><button className="amari-game__speak" onClick={()=>setSpeak(true)}>I said it. Show the spine.</button>{speak&&<div className="amari-game__answer"><b>{spine}</b><p>Did you include private, hands-on guided movement and a felt change?</p></div>}</>:<div className="amari-game__choices">{t.a.map((x,n)=><button key={x} disabled={checked} className={pick===n?'is-selected':''} onClick={()=>setPick(n)}>{x}</button>)}</div>}{checked&&!last&&<div className={`amari-game__feedback ${good?'is-right':'is-miss'}`}><b>{good?'That is it.':'Not quite.'}</b><p>{t.why}</p></div>}</main><footer><button disabled={last?!speak:pick===null} onClick={()=>checked?next():setChecked(true)}>{checked?(last?'Finish round':'Continue'):'Check'} <ChevronRight size={18}/></button></footer>{last&&checked&&<div className="amari-game__finish"><b>{miss?`${miss} answer${miss>1?'s need':' needs'} another pass.`:'Clean first pass.'}</b><button onClick={()=>{setI(0);setMiss(0);setPick(null);setChecked(false);setSpeak(false)}}><RotateCcw size={17}/> Replay</button></div>}</section>}
