import { describe, expect, it, vi } from 'vitest';
import { generateKeyPairSync, sign, createHash, verify } from 'node:crypto';
import { EventEmitter } from 'node:events';
import { PassThrough } from 'node:stream';
import { readFileSync } from 'node:fs';
import { SIGNING_RECORD_KEYS, SIGNING_LIMITS, inspectRehearsalSigning, signRehearsalArtifact } from '../../scripts/follow-up-rehearsal-signing.mjs';
import { HOST_RECORD_KEYS, hostApprovalSigningBytes, validateHostApproval, runExactBwsRecord } from '../../scripts/follow-up-rehearsal-host.mjs';
import { VERSION, ACTION_DIGEST, canonical, encode, manifestSigningBytes, requestSigningBytes, authenticate } from '../../follow-up-rehearsal-worker/src/protocol.mjs';
import { validateCallerConfiguration } from '../../follow-up-rehearsal-worker/src/caller-authorization.mjs';
import { FOLLOW_UP_REGISTRY_SCHEMA_DIGEST } from '../../scripts/lib/follow-up-evidence-storage-adapters.mjs';

const H = x => createHash('sha256').update(x).digest('hex'), id = x => 'id_' + H(x), DAY = 86400000;
const roles = ['root', 'owner', 'operator', 'reader', 'admission', 'capture', 'floor', 'receipt', 'witness', 'source', 'hostApproval'];
const pairs = Object.fromEntries(roles.map(role => [role, generateKeyPairSync('ed25519')]));
const pem = role => pairs[role].publicKey.export({ type: 'spki', format: 'pem' }), privatePem = role => pairs[role].privateKey.export({ type: 'pkcs8', format: 'pem' }), fp = role => H(pairs[role].publicKey.export({ type: 'spki', format: 'der' }));
const custody = { executable: '/reviewed/bws', executableSha256: H('reviewed executable') };
const uid = i => `${String(i).repeat(8)}-${String(i).repeat(4)}-4${String(i).repeat(3)}-8${String(i).repeat(3)}-${String(i).repeat(12)}`;
const record = role => ({ id: uid(1), key: SIGNING_RECORD_KEYS[role], projectId: uid(2), organizationId: uid(3), revisionDate: '2026-08-28T01:00:00.000000000Z', sha256: H(privatePem(role)) });
function fixture() {
  const now = Date.now(), at = now - 100, scope = { accountId: id('account'), targetId: id('target'), actionScopeDigest: H('action scope'), environment: 'synthetic', sinkId: id('sink'), registryId: id('registry'), schemaDigest: FOLLOW_UP_REGISTRY_SCHEMA_DIGEST, sourceRevision: 'a'.repeat(40), actionDigest: ACTION_DIGEST, handlerDigest: H('control'), epoch: id('epoch'), generation: 1, issuerReleaseDigest: H('issuer'), policyVersion: 'follow-up-retention-policy.v1' };
  const body = { version: VERSION, transport: 'private_service_binding_rpc', scope, origin: { sourceId: id('source'), sequence: 1, originalAt: at - 1000, approvedAt: at, dispatchUntil: at + 240000 }, aliasSetDigest: H('aliases'), replayHorizonUntil: at + 10 * DAY, retentionUntil: at + DAY - 2000, parentDeadline: at + DAY, deletionDeadline: null, issuedAt: at, expiresAt: at + 3600000, issuerSequence: 1, principals: ['owner', 'operator', 'reader'].map(role => ({ callerId: id('caller/' + role), keyId: id(role), publicKeySha256: fp(role), role, notBefore: at, expiresAt: at + 3600000 })), signers: Object.fromEntries(roles.slice(4, 10).map(role => [role, { keyId: id(role), publicKeySha256: fp(role) }])) };
  const root = { keyId: id('root'), publicKey: pem('root') }, principals = Object.fromEntries(['owner', 'operator', 'reader'].map(role => [role, pem(role)])), services = Object.fromEntries(roles.slice(4, 10).map(role => [role, pem(role)]));
  const manifest = { kind: 'manifest', body, context: { root, principals, services }, custody, record: record('root') };
  const publicConfig = { REHEARSAL_MANIFEST: encode({ body, keyId: root.keyId, signature: sign(null, manifestSigningBytes(body), pairs.root.privateKey).toString('base64') }), REHEARSAL_CALLER_KEYS: encode({ root, principals }) };
  const request = (action = 'execute', role = ['bootstrap', 'revoke'].includes(action) ? 'owner' : ['status', 'result'].includes(action) ? 'reader' : 'operator') => ({ kind: 'request', body: { version: VERSION, manifestDigest: H(manifestSigningBytes(body)), scopeDigest: H(canonical(scope)), callerId: id('caller/' + role), role, action, body: action === 'revoke' ? { keyId: id('operator') } : {}, nonce: H('explicit unchanged nonce'), issuedAt: now - 1, expiresAt: now + 29999 }, context: publicConfig, custody, record: record(role) });
  const trustedRoot = { keyId: 'host-owner-v1', publicKey: pem('hostApproval') };
  const records = Object.fromEntries(['github', 'cloudflare', 'issuer', 'control', 'caller'].map((role, i) => [role, { id: uid(i + 1), key: HOST_RECORD_KEYS[role], projectId: uid(7), organizationId: uid(8), revisionDate: '2026-08-28T01:00:00Z', sha256: H('public expected record digest/' + role) }]));
  const host = { kind: 'host-approval', body: { version: 'follow-up-rehearsal-host-approval.v1', mode: 'deploy', releaseId: H('release'), issuedAt: at, expiresAt: at + 3600000, reviewedRevision: scope.sourceRevision, hostArtifactDigest: H('host artifact'), ownerKeyId: trustedRoot.keyId, custody: { ...custody, records }, ledger: { repository: 'Eben283/amarimethod-website', refPrefix: 'refs/tags/followup-rehearsal-consumed/', rulesetId: 123 }, operation: { approvalDigest: H('deployment approval') } }, context: { trustedRoot, requestText: null }, custody, record: record('hostApproval') };
  return { manifest, request, host, publicConfig };
}
const options = intent => ({ execute: true, approvedDigest: inspectRehearsalSigning(intent).approvedDigest, intent });
function fakeCustody(role, edit = value => value) {
  const returned = [], calls = [];
  const runBws = async input => { calls.push(input); const value = edit({ ...input.record, value: privatePem(role) }); returned.push(value); return value; };
  return { runBws, returned, calls };
}
function hostInvocation() {
  const f = fixture(), request = f.request(), requestText = encode({ body: request.body, keyId: id('operator'), signature: sign(null, requestSigningBytes(request.body), pairs.operator.privateKey).toString('base64') });
  const rsa = generateKeyPairSync('rsa', { modulusLength: 2048 }).publicKey.export({ format: 'jwk' }), at = f.manifest.body.issuedAt;
  const principal = { callerId: id('caller/operator'), keyId: id('operator'), role: 'operator' };
  const access = { version: 'follow-up-operator-access.v1', origin: 'https://fixture.amarimethod.com', issuer: 'https://fixture.cloudflareaccess.com', audience: H('audience'), manifestDigest: request.body.manifestDigest, scopeDigest: request.body.scopeDigest, issuedAt: at, expiresAt: f.manifest.body.expiresAt, jwks: [{ kid: 'fixture', kty: 'RSA', alg: 'RS256', use: 'sig', n: rsa.n, e: rsa.e }], principals: [{ commonName: 'f'.repeat(32) + '.access', ...principal }] };
  f.host.body.mode = 'invoke'; f.host.body.operation = { origin: access.origin, path: '/v1/rehearsal', envelopeDigest: H(requestText), publicConfig: { ...f.publicConfig, OPERATOR_ACCESS_CONFIG: encode(access) }, principal };
  f.host.body.custody.records = Object.fromEntries(['github', 'accessId', 'accessSecret'].map((role, i) => [role, { ...f.host.body.custody.records.github, id: uid(i + 1), key: HOST_RECORD_KEYS[role] }]));
  f.host.context.requestText = requestText; return f.host;
}

describe('typed existing-record rehearsal signing', () => {
  it.each(['manifest', 'request', 'host'])('public inspection of %s performs no credential retrieval or authorization', kind => { const f = fixture(), intent = kind === 'request' ? f.request() : f[kind], result = inspectRehearsalSigning(intent); expect(result).toMatchObject({ credentialRead: false, executionAuthorized: false, keyCreationAvailable: false, recordCreationAvailable: false }); expect(result.approvedDigest).toMatch(/^[a-f0-9]{64}$/); expect(JSON.stringify(result)).not.toContain('PRIVATE KEY'); });
  it('signs a manifest with all ten public identities checked by frozen validators', async () => { const f = fixture(), bws = fakeCustody('root'), result = await signRehearsalArtifact(options(f.manifest), bws); expect(result.artifact.body).toEqual(f.manifest.body); expect(verify(null, manifestSigningBytes(f.manifest.body), pairs.root.publicKey, Buffer.from(result.artifact.signature, 'base64'))).toBe(true); expect(validateCallerConfiguration({ ...f.publicConfig, REHEARSAL_MANIFEST: result.text }).manifestDigest).toBe(H(manifestSigningBytes(f.manifest.body))); expect(bws.calls).toHaveLength(1); expect(bws.returned[0].value).toBeUndefined(); });
  it.each(['bootstrap', 'admit', 'execute', 'status', 'result', 'revoke'])('signs only the allowed principal for %s without changing original nonce or clocks', async action => { const f = fixture(), intent = f.request(action), bws = fakeCustody(intent.body.role), result = await signRehearsalArtifact(options(intent), bws); expect(result.artifact.body).toEqual(intent.body); expect(authenticate(validateCallerConfiguration(f.publicConfig), result.text).r.action).toBe(action); expect(result).toMatchObject({ credentialGets: 1, persisted: false, deployed: false, invoked: false }); expect(JSON.stringify(result)).not.toContain('PRIVATE KEY'); expect(JSON.stringify(result)).not.toContain('"value"'); });
  it.each(['deploy', 'deploy-gateway', 'attach-gateway'])('signs exact validated %s host policy using separate host authority', async mode => { const f = fixture(), intent = f.host; intent.body.mode = mode; if (mode !== 'deploy') intent.body.custody.records = Object.fromEntries(['github', 'cloudflare'].map(role => [role, intent.body.custody.records[role]])); const result = await signRehearsalArtifact(options(intent), fakeCustody('hostApproval')); expect(validateHostApproval(result.artifact, intent.context.trustedRoot)).toEqual(intent.body); expect(verify(null, hostApprovalSigningBytes(intent.body), pairs.hostApproval.publicKey, Buffer.from(result.artifact.signature, 'base64url'))).toBe(true); });
  it('signs a host invoke approval only for the already-signed exact request and Access principal', async () => { const intent = hostInvocation(), inspected = inspectRehearsalSigning(intent), result = await signRehearsalArtifact(options(intent), fakeCustody('hostApproval')); expect(inspected.expiresAt).toBe(JSON.parse(intent.context.requestText).body.expiresAt); expect(validateHostApproval(result.artifact, intent.context.trustedRoot)).toEqual(intent.body); expect(result.artifact.policy.operation.envelopeDigest).toBe(H(intent.context.requestText)); });
  it.each(['request-digest', 'request-signature', 'principal', 'host-key-collision', 'extra-policy', 'mode'])('rejects host %s before retrieving signing credentials', kind => {
    const intent = hostInvocation(); if (kind === 'request-digest') intent.body.operation.envelopeDigest = H('other');
    if (kind === 'request-signature') { const value = JSON.parse(intent.context.requestText); value.signature = 'A'.repeat(86) + '=='; intent.context.requestText = encode(value); intent.body.operation.envelopeDigest = H(intent.context.requestText); }
    if (kind === 'principal') intent.body.operation.principal.role = 'owner'; if (kind === 'host-key-collision') intent.context.trustedRoot.publicKey = pem('operator'); if (kind === 'extra-policy') intent.body.retry = true; if (kind === 'mode') intent.body.mode = 'create-resources';
    expect(() => inspectRehearsalSigning(intent)).toThrow('rehearsal_signing_refused');
  });
  it.each(['execute', 'digest', 'missing', 'raw-bytes'])('refuses %s without opening custody', async kind => { const input = options(fixture().request()), runBws = vi.fn(); if (kind === 'execute') input.execute = false; if (kind === 'digest') input.approvedDigest = H('wrong'); if (kind === 'missing') delete input.approvedDigest; if (kind === 'raw-bytes') input.intent.kind = 'raw-bytes'; await expect(signRehearsalArtifact(input, { runBws })).rejects.toThrow('rehearsal_signing_refused'); expect(runBws).not.toHaveBeenCalled(); });
  it.each(['id', 'key', 'projectId', 'organizationId', 'revisionDate'])('checks exact returned %s metadata before accessing value', async field => { const intent = fixture().request(), input = options(intent), getValue = vi.fn(() => privatePem('operator')), returned = { ...intent.record, [field]: 'mismatched' }; Object.defineProperty(returned, 'value', { get: getValue, configurable: true }); await expect(signRehearsalArtifact(input, { runBws: async () => returned })).rejects.toThrow(); expect(getValue).not.toHaveBeenCalled(); });
  it.each(['hash', 'public-key', 'algorithm', 'aggregate', 'oversize'])('rejects %s private record without returning secret material', async kind => { const intent = fixture().request(); let value = privatePem('operator'); if (kind === 'public-key') value = privatePem('owner'); if (kind === 'algorithm') value = generateKeyPairSync('ec', { namedCurve: 'prime256v1' }).privateKey.export({ type: 'pkcs8', format: 'pem' }); if (kind === 'aggregate') value = JSON.stringify({ owner: privatePem('owner'), operator: value }); if (kind === 'oversize') value = 'x'.repeat(SIGNING_LIMITS.privateKeyBytes + 1); if (kind !== 'hash') intent.record.sha256 = H(value); const returned = { ...intent.record, value: kind === 'hash' ? 'mismatched' : value }; await expect(signRehearsalArtifact(options(intent), { runBws: async () => returned })).rejects.toThrow('rehearsal_signing_refused'); expect(returned.value).toBeUndefined(); });
  it.each(['role', 'scope', 'manifest', 'expiry', 'future', 'lifetime', 'nonce', 'action', 'unknown-field'])('rejects request %s before custody', async kind => { const intent = fixture().request(); if (kind === 'role') intent.body.action = 'bootstrap'; if (kind === 'scope') intent.body.scopeDigest = H('other'); if (kind === 'manifest') intent.body.manifestDigest = H('other'); if (kind === 'expiry') { intent.body.expiresAt = Date.now() - 1; intent.body.issuedAt = Date.now() - 30000; } if (kind === 'future') { intent.body.issuedAt = Date.now() + 10; intent.body.expiresAt = Date.now() + 30000; } if (kind === 'lifetime') intent.body.expiresAt = intent.body.issuedAt + 30001; if (kind === 'nonce') intent.body.nonce = '0'.repeat(64); if (kind === 'action') intent.body.action = 'retry'; if (kind === 'unknown-field') intent.body.url = 'https://other.example.com'; expect(() => inspectRehearsalSigning(intent)).toThrow('rehearsal_signing_refused'); });
  it.each(['root-key-id', 'root-caller-id', 'root-fingerprint', 'principal-id', 'principal-fingerprint', 'service-id', 'service-fingerprint', 'service-material', 'missing-service', 'private-public-key', 'production'])('rejects manifest %s identity collision or invalid declaration', kind => { const { manifest: intent } = fixture(); if (kind === 'root-key-id') intent.context.root.keyId = intent.body.principals[0].keyId; if (kind === 'root-caller-id') intent.context.root.keyId = intent.body.principals[0].callerId; if (kind === 'root-fingerprint') intent.context.root.publicKey = pem('owner'); if (kind === 'principal-id') intent.body.principals[1].keyId = intent.body.principals[0].keyId; if (kind === 'principal-fingerprint') intent.body.principals[1].publicKeySha256 = intent.body.principals[0].publicKeySha256; if (kind === 'service-id') intent.body.signers.admission.keyId = intent.body.principals[0].keyId; if (kind === 'service-fingerprint') intent.body.signers.admission.publicKeySha256 = fp('owner'); if (kind === 'service-material') intent.context.services.admission = pem('capture'); if (kind === 'missing-service') delete intent.context.services.floor; if (kind === 'private-public-key') intent.context.root.publicKey = privatePem('root'); if (kind === 'production') intent.body.scope.environment = 'production'; expect(() => inspectRehearsalSigning(intent)).toThrow(); });
  it.each(['record-key', 'uuid', 'revision', 'future-revision', 'binary', 'unknown-custody', 'unknown-record'])('rejects %s custody target before retrieval', kind => { const intent = fixture().request(); if (kind === 'record-key') intent.record.key = SIGNING_RECORD_KEYS.owner; if (kind === 'uuid') intent.record.id = 'not-a-uuid'; if (kind === 'revision') intent.record.revisionDate = 'yesterday'; if (kind === 'future-revision') intent.record.revisionDate = '2099-01-01T00:00:00Z'; if (kind === 'binary') intent.custody = { ...custody, executable: '/reviewed/../bws' }; if (kind === 'unknown-custody') intent.custody = { ...custody, profile: 'default' }; if (kind === 'unknown-record') intent.record.value = 'forbidden'; expect(() => inspectRehearsalSigning(intent)).toThrow(); });
  it.each(['getter', 'toJSON', 'depth', 'oversize', 'prototype'])('rejects %s object input without evaluating executable properties', kind => { const intent = fixture().request(), get = vi.fn(() => 'forbidden'); if (kind === 'getter') Object.defineProperty(intent, 'body', { get, enumerable: true }); if (kind === 'toJSON') intent.toJSON = get; if (kind === 'depth') { let v = intent; for (let i = 0; i < 20; i++) v = v.extra = {}; } if (kind === 'oversize') intent.extra = 'x'.repeat(SIGNING_LIMITS.inputBytes + 1); if (kind === 'prototype') Object.setPrototypeOf(intent, { injected: true }); expect(() => inspectRehearsalSigning(intent)).toThrow(); expect(get).not.toHaveBeenCalled(); });
  it('detaches inputs and custody arguments before waiting so caller/transport mutation cannot change signed bytes or trust', async () => { const intent = fixture().request(), input = options(intent), original = structuredClone(intent); let release, returned; const held = new Promise(resolve => { release = resolve; }); const pending = signRehearsalArtifact(input, { runBws: async arg => { returned = { ...arg.record, value: privatePem('operator') }; arg.record.sha256 = H('transport mutation'); await held; return returned; } }); intent.body.nonce = H('mutated'); intent.record.sha256 = H('mutated'); intent.context.REHEARSAL_MANIFEST = '{}'; release(); const result = await pending; expect(result.artifact.body).toEqual(original.body); expect(returned.value).toBeUndefined(); });
  it('rechecks original request expiry after credential retrieval and releases late record references', async () => { vi.useFakeTimers({ toFake: ['Date'] }); try { const intent = fixture().request(), input = options(intent), returned = { ...intent.record, value: privatePem('operator') }; const runBws = async () => { vi.setSystemTime(intent.body.expiresAt); return returned; }; await expect(signRehearsalArtifact(input, { runBws })).rejects.toThrow('rehearsal_signing_refused'); expect(returned.value).toBeUndefined(); } finally { vi.useRealTimers(); } });
  it('times out one ignored-abort retrieval without retry or a late signature', async () => { vi.useFakeTimers(); try { const intent = fixture().request(), input = options(intent), returned = { ...intent.record, value: privatePem('operator') }; let release; const held = new Promise(resolve => { release = resolve; }), runBws = vi.fn(async () => held); const pending = signRehearsalArtifact(input, { runBws }); const rejected = expect(pending).rejects.toThrow('rehearsal_signing_refused'); await vi.advanceTimersByTimeAsync(SIGNING_LIMITS.operationMs + 1); await rejected; release(returned); await Promise.resolve(); await Promise.resolve(); expect(returned.value).toBeUndefined(); expect(runBws).toHaveBeenCalledTimes(1); } finally { vi.useRealTimers(); } });
  it('composes the actual no-cache exact-record subprocess adapter with in-process signing', async () => { const intent = fixture().request(); let captured, bootstrap; const runBws = arg => runExactBwsRecord(arg, { inspectBinary() {}, readBootstrap: () => (bootstrap = Buffer.from('synthetic-bootstrap')), spawn: (binary, args, opts) => { captured = { binary, args, opts }; const child = new EventEmitter(); child.stdout = new PassThrough(); child.stderr = new PassThrough(); child.kill = () => {}; queueMicrotask(() => { child.stdout.end(JSON.stringify({ ...arg.record, value: privatePem('operator') })); child.emit('close', 0); }); return child; } }); const result = await signRehearsalArtifact(options(intent), { runBws }); expect(result.role).toBe('operator'); expect(captured.args).toEqual(['secret', 'get', intent.record.id, '--output', 'json', '--color', 'no', '--config-file', expect.stringMatching(/follow-up-rehearsal-bws\.toml$/), '--profile', 'rehearsal']); expect(captured.opts.env).toEqual({ BWS_ACCESS_TOKEN: 'synthetic-bootstrap' }); expect(JSON.stringify(captured.args)).not.toContain('PRIVATE KEY'); expect(bootstrap.every(byte => byte === 0)).toBe(true); });
  it('contains no key/record creation, CLI, persistence or provider invocation path', () => { const source = readFileSync(new URL('../../scripts/follow-up-rehearsal-signing.mjs', import.meta.url), 'utf8'); expect(source).not.toMatch(/generateKey|writeFile|appendFile|process\.argv|process\.env|console\.|\bfetch\s*\(|secret create|secret list/); expect(source).toContain('dependencies.runBws ?? runExactBwsRecord'); });
});
