import { describe, expect, it, vi } from 'vitest';
import { generateKeyPairSync, sign, createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { validateRehearsalAccessReadback, ACCESS_READBACK_LIMITS } from '../../scripts/lib/follow-up-rehearsal-access-readback.mjs';
import { VERSION, ACTION_DIGEST, canonical, encode, manifestSigningBytes } from '../../follow-up-rehearsal-worker/src/protocol.mjs';
import { FOLLOW_UP_REGISTRY_SCHEMA_DIGEST } from '../../scripts/lib/follow-up-evidence-storage-adapters.mjs';

const H = value => createHash('sha256').update(value).digest('hex'), id = value => 'id_' + H(value), DAY = 86400000;
const uuid = n => `${String(n).repeat(8)}-${String(n).repeat(4)}-4${String(n).repeat(3)}-8${String(n).repeat(3)}-${String(n).repeat(12)}`;
const roles = ['root', 'owner', 'operator', 'reader', 'admission', 'capture', 'floor', 'receipt', 'witness', 'source'];
const pairs = Object.fromEntries(roles.map(role => [role, generateKeyPairSync('ed25519')]));
const pem = role => pairs[role].publicKey.export({ type: 'spki', format: 'pem' }), fp = role => H(pairs[role].publicKey.export({ type: 'spki', format: 'der' }));
const rsa = generateKeyPairSync('rsa', { modulusLength: 2048 }), otherRsa = generateKeyPairSync('rsa', { modulusLength: 2048 });
// Minimal real X.509 fixture assembled and signed only in memory. No dependency,
// filesystem private key, subprocess, network or fixture credential is involved.
function certificate(pair, from = Date.now() - DAY, until = Date.now() + DAY) {
  const der = (tag, ...parts) => { const body = Buffer.concat(parts); let length = Buffer.from([body.length]); if (body.length >= 128) { let hex = body.length.toString(16); if (hex.length % 2) hex = '0' + hex; const bytes = Buffer.from(hex, 'hex'); length = Buffer.concat([Buffer.from([128 + bytes.length]), bytes]); } return Buffer.concat([Buffer.from([tag]), length, body]); };
  const seq = (...parts) => der(48, ...parts), algorithm = Buffer.from('300d06092a864886f70d01010b0500', 'hex');
  const name = seq(der(49, seq(Buffer.from('0603550403', 'hex'), der(12, Buffer.from('synthetic-access-fixture')))));
  const time = value => der(24, Buffer.from(new Date(value).toISOString().replace(/[-:]/g, '').replace('T', '').replace(/\.\d{3}Z$/, 'Z')));
  const tbs = seq(der(160, der(2, Buffer.from([2]))), der(2, Buffer.from([1])), algorithm, name, seq(time(from), time(until)), name, pair.publicKey.export({ type: 'spki', format: 'der' }));
  const bytes = seq(tbs, algorithm, der(3, Buffer.from([0]), sign('RSA-SHA256', tbs, pair.privateKey)));
  return '-----BEGIN CERTIFICATE-----\n' + bytes.toString('base64').match(/.{1,64}/g).join('\n') + '\n-----END CERTIFICATE-----\n';
}
const cert = certificate(rsa), otherCert = certificate(otherRsa);
const envelope = result => ({ success: true, errors: [], messages: [], result });
const list = result => ({ ...envelope(result), result_info: { page: 1, per_page: 100, count: result.length, total_count: result.length, total_pages: 1 } });
function fixture() {
  const at = Date.now() - 100, scope = { accountId: id('account'), targetId: id('target'), actionScopeDigest: H('action scope'), environment: 'synthetic', sinkId: id('sink'), registryId: id('registry'), schemaDigest: FOLLOW_UP_REGISTRY_SCHEMA_DIGEST, sourceRevision: 'a'.repeat(40), actionDigest: ACTION_DIGEST, handlerDigest: H('control'), epoch: id('epoch'), generation: 1, issuerReleaseDigest: H('issuer'), policyVersion: 'follow-up-retention-policy.v1' };
  const body = { version: VERSION, transport: 'private_service_binding_rpc', scope, origin: { sourceId: id('source'), sequence: 1, originalAt: at - 1000, approvedAt: at, dispatchUntil: at + 240000 }, aliasSetDigest: H('aliases'), replayHorizonUntil: at + 10 * DAY, retentionUntil: at + DAY - 2000, parentDeadline: at + DAY, deletionDeadline: null, issuedAt: at, expiresAt: at + 3600000, issuerSequence: 1, principals: ['owner', 'operator', 'reader'].map(role => ({ callerId: id('caller/' + role), keyId: id(role), publicKeySha256: fp(role), role, notBefore: at, expiresAt: at + 3600000 })), signers: Object.fromEntries(roles.slice(4).map(role => [role, { keyId: id(role), publicKeySha256: fp(role) }])) };
  const root = { keyId: id('root'), publicKey: pem('root') }, jwk = { ...rsa.publicKey.export({ format: 'jwk' }), kid: 'fixture-current-key', alg: 'RS256', use: 'sig' };
  const access = { version: 'follow-up-operator-access.v1', origin: 'https://rehearsal.amarimethod.com', issuer: 'https://fixture.cloudflareaccess.com', audience: H('audience'), manifestDigest: H(manifestSigningBytes(body)), scopeDigest: H(canonical(scope)), issuedAt: at, expiresAt: body.expiresAt, jwks: [jwk], principals: body.principals.map(p => ({ commonName: H(p.role).slice(0, 32) + '.access', callerId: p.callerId, keyId: p.keyId, role: p.role })) };
  const publicConfig = { REHEARSAL_MANIFEST: encode({ body, keyId: root.keyId, signature: sign(null, manifestSigningBytes(body), pairs.root.privateKey).toString('base64') }), REHEARSAL_CALLER_KEYS: encode({ root, principals: Object.fromEntries(['owner', 'operator', 'reader'].map(role => [role, pem(role)])) }), OPERATOR_ACCESS_CONFIG: encode(access) };
  const app = { id: uuid(1), type: 'self_hosted', domain: 'rehearsal.amarimethod.com', aud: access.audience, name: 'Synthetic rehearsal', destinations: [{ type: 'public', uri: 'rehearsal.amarimethod.com' }], allow_authenticate_via_warp: false, options_preflight_bypass: false, app_launcher_visible: false, service_auth_401_redirect: true, session_duration: '1h' };
  const tokenIds = [uuid(3), uuid(4), uuid(5)], policies = [{ id: uuid(2), decision: 'non_identity', include: tokenIds.map(token_id => ({ service_token: { token_id } })), exclude: [], require: [], precedence: 0, session_duration: '30m' }];
  const serviceTokens = access.principals.map((p, i) => ({ id: tokenIds[i], client_id: p.commonName, name: 'Synthetic ' + p.role, enabled: true, expires_at: new Date(at + 7200000).toISOString(), duration: '2h', created_at: new Date(at - 1000).toISOString(), updated_at: new Date(at - 1000).toISOString(), last_seen_at: null }));
  return { publicConfig, applicationId: app.id, policyIds: [uuid(2)], serviceTokenIds: tokenIds, organization: envelope({ auth_domain: 'fixture.cloudflareaccess.com', name: 'Synthetic organization', session_duration: '24h' }), application: envelope(app), applications: list([structuredClone(app)]), zoneApplications: list([]), policies: list(policies), serviceTokens: list(serviceTokens), jwks: { keys: [jwk], public_cert: { kid: jwk.kid, cert }, public_certs: [{ kid: jwk.kid, cert }] }, observedAt: Date.now() };
}

describe('existing Access readback verification', () => {
  it('verifies complete raw Cloudflare envelopes and real X509/JWK bytes without claiming issuance or custody', () => { const f = fixture(), result = validateRehearsalAccessReadback(f); expect(result).toMatchObject({ applicationId: f.applicationId, policyIds: f.policyIds, serviceTokenIds: f.serviceTokenIds, issuanceProven: false, custodyProven: false, productionAuthority: false }); expect(result.digest).toMatch(/^[a-f0-9]{64}$/); expect(result.freshnessUntil).toBe(f.observedAt + ACCESS_READBACK_LIMITS.ageMs); expect(JSON.stringify(result)).not.toMatch(/client_id|\.access|CERTIFICATE|PUBLIC KEY|last_seen/); });
  it('keeps digest stable across observation times, inventory order and volatile last_seen', () => { const f = fixture(), before = validateRehearsalAccessReadback(f).digest; f.observedAt -= 1; f.serviceTokens.result.reverse(); f.serviceTokens.result[0].last_seen_at = new Date().toISOString(); f.serviceTokenIds.reverse(); expect(validateRehearsalAccessReadback(f).digest).toBe(before); });
  it('changes digest when validated policy semantics or token version changes', () => { const f = fixture(), before = validateRehearsalAccessReadback(f).digest; f.policies.result[0].session_duration = '20m'; expect(validateRehearsalAccessReadback(f).digest).not.toBe(before); f.policies.result[0].session_duration = '30m'; f.serviceTokens.result[0].client_secret_version = 2; expect(validateRehearsalAccessReadback(f).digest).not.toBe(before); });
  it('accepts identical selected app in legacy zone readback but not conflicting bytes', () => { const f = fixture(); f.zoneApplications = list([structuredClone(f.application.result)]); expect(validateRehearsalAccessReadback(f).digest).toBe(validateRehearsalAccessReadback({ ...f, zoneApplications: list([]) }).digest); f.zoneApplications.result[0].options_preflight_bypass = true; expect(() => validateRehearsalAccessReadback(f)).toThrow(); });
  it('allows demonstrably unrelated public hostname and scoped path applications', () => { const f = fixture(); f.applications = list([...f.applications.result, { id: uuid(7), type: 'self_hosted', domain: 'other.amarimethod.com/admin', destinations: [{ type: 'public', uri: 'other.amarimethod.com/admin' }] }]); expect(validateRehearsalAccessReadback(f).issuanceProven).toBe(false); });
  it.each(['id_only', 'account_link', 'account_precedence_link', 'expanded'])('accepts official reusable/expanded application policy representation %s', kind => {
    const f = fixture(), before = validateRehearsalAccessReadback(f).digest;
    const link = { id: f.policyIds[0] };
    if (kind === 'account_link' || kind === 'account_precedence_link') link.account_id = 'fa2b6f2441129b259dd5dea74045721b';
    if (kind === 'account_precedence_link') link.precedence = f.policies.result[0].precedence;
    f.application.result.policies = [kind === 'expanded' ? structuredClone(f.policies.result[0]) : link];
    expect(validateRehearsalAccessReadback(f).digest).toBe(before);
  });
  it.each(['account_id', 'precedence', 'unknown_field'])('rejects mismatched or unknown reusable policy link %s', kind => {
    const f = fixture(), link = { id: f.policyIds[0], account_id: 'fa2b6f2441129b259dd5dea74045721b', precedence: 0 };
    if (kind === 'account_id') link.account_id = 'a'.repeat(32);
    if (kind === 'precedence') link.precedence = 1;
    if (kind === 'unknown_field') link.authorization = true;
    f.application.result.policies = [link];
    expect(() => validateRehearsalAccessReadback(f)).toThrow('rehearsal_access_readback_refused');
  });
  it.each(['applications', 'zoneApplications', 'policies', 'serviceTokens'])('requires complete %s inventory', field => { const f = fixture(); f[field].result_info.total_count++; expect(() => validateRehearsalAccessReadback(f)).toThrow('rehearsal_access_readback_refused'); });
  it.each(['cursor', 'page', 'total_pages', 'count', 'missing_info', 'oversize', 'missing_zone'])('refuses %s pagination evidence', kind => { const f = fixture(); if (kind === 'cursor') f.applications.result_info.cursor = 'next'; if (kind === 'page') f.applications.result_info.page = 2; if (kind === 'total_pages') f.applications.result_info.total_pages = 2; if (kind === 'count') f.applications.result_info.count = 0; if (kind === 'missing_info') delete f.applications.result_info; if (kind === 'oversize') f.applications.result_info.per_page = 101; if (kind === 'missing_zone') delete f.zoneApplications; expect(() => validateRehearsalAccessReadback(f)).toThrow(); });
  it.each(['success', 'errors', 'messages', 'missing_result', 'unknown_envelope'])('rejects malformed envelope %s', kind => { const f = fixture(); if (kind === 'success') f.application.success = false; if (kind === 'errors') f.application.errors.push({ message: 'error' }); if (kind === 'messages') f.application.messages.push({ message: 'unreviewed' }); if (kind === 'missing_result') delete f.application.result; if (kind === 'unknown_envelope') f.application.cursor = 'next'; expect(() => validateRehearsalAccessReadback(f)).toThrow(); });
  it.each(['stale', 'future', 'organization', 'audience', 'applicationId', 'policyIds', 'serviceTokenIds', 'publicConfig'])('rejects mismatched %s evidence', kind => { const f = fixture(); if (kind === 'stale') f.observedAt -= 30001; if (kind === 'future') f.observedAt += 10000; if (kind === 'organization') f.organization.result.auth_domain = 'other.cloudflareaccess.com'; if (kind === 'audience') f.application.result.aud = H('other'); if (kind === 'applicationId') f.applicationId = uuid(6); if (kind === 'policyIds') f.policyIds = [uuid(6)]; if (kind === 'serviceTokenIds') f.serviceTokenIds[0] = uuid(6); if (kind === 'publicConfig') f.publicConfig.REHEARSAL_MANIFEST = '{}'; expect(() => validateRehearsalAccessReadback(f)).toThrow(); });
  it.each(['preflight', 'warp', 'launcher', 'redirect', 'domain_path', 'domain_alias', 'duplicate_destination', 'unknown_destination', 'unknown_app_field', 'oauth', 'scim', 'header', 'long_session', 'forever_session', 'invalid_session'])('rejects selected app %s', kind => { const f = fixture(), app = f.application.result; if (kind === 'preflight') app.options_preflight_bypass = true; if (kind === 'warp') app.allow_authenticate_via_warp = true; if (kind === 'launcher') app.app_launcher_visible = true; if (kind === 'redirect') app.service_auth_401_redirect = false; if (kind === 'domain_path') app.domain += '/v1/rehearsal'; if (kind === 'domain_alias') app.self_hosted_domains = ['other.amarimethod.com']; if (kind === 'duplicate_destination') app.destinations.push({ ...app.destinations[0] }); if (kind === 'unknown_destination') app.destinations = [{ type: 'future' }]; if (kind === 'unknown_app_field') app.future_route = 'other'; if (kind === 'oauth') app.oauth_configuration = { enabled: true }; if (kind === 'scim') app.scim_config = {}; if (kind === 'header') app.read_service_tokens_from_header = 'Authorization'; if (kind === 'long_session') app.session_duration = '2h'; if (kind === 'forever_session') app.session_duration = 'forever'; if (kind === 'invalid_session') app.session_duration = '1h1h'; expect(() => validateRehearsalAccessReadback(f)).toThrow(); });
  it.each(['rehearsal.amarimethod.com', 'rehearsal.amarimethod.com/v1/rehearsal', '*.amarimethod.com/v1/*', '*method.com/other'])('rejects account application route overlap %s', domain => { const f = fixture(); f.applications = list([...f.applications.result, { id: uuid(6), type: 'self_hosted', domain }]); expect(() => validateRehearsalAccessReadback(f)).toThrow(); });
  it('rejects more specific legacy zone override even when account inventory is clean', () => { const f = fixture(); f.zoneApplications = list([{ id: uuid(6), type: 'self_hosted', domain: 'rehearsal.amarimethod.com/v1/rehearsal' }]); expect(() => validateRehearsalAccessReadback(f)).toThrow(); });
  it.each(['all_workers', 'all_preview_workers', 'worker', 'preview_worker', 'private', 'via_mcp_server_portal', 'future'])('rejects %s destination without assuming Worker ID/name equivalence', type => { const f = fixture(); f.applications = list([...f.applications.result, { id: uuid(6), type: 'self_hosted', domain: 'other.amarimethod.com', destinations: [{ type, worker_id: 'unproven-identity' }] }]); expect(() => validateRehearsalAccessReadback(f)).toThrow(); });
  it.each(['allow', 'bypass', 'deny', 'group', 'everyone', 'any_service_token', 'extra_include', 'require', 'duplicate_precedence', 'unknown_field', 'embedded_policy_mismatch'])('rejects policy %s', kind => { const f = fixture(), p = f.policies.result[0]; if (['allow', 'bypass', 'deny'].includes(kind)) p.decision = kind; if (['group', 'everyone', 'any_service_token'].includes(kind)) p.include = [{ [kind]: {} }]; if (kind === 'extra_include') p.include.push({ service_token: { token_id: uuid(9) } }); if (kind === 'require') p.require = [{ ip: { ip: '192.0.2.0/24' } }]; if (kind === 'duplicate_precedence') { f.policyIds.push(uuid(8)); f.policies = list([p, { ...p, id: uuid(8) }]); } if (kind === 'unknown_field') p.retry = true; if (kind === 'embedded_policy_mismatch') f.application.result.policies = [{ id: uuid(9) }]; expect(() => validateRehearsalAccessReadback(f)).toThrow(); });
  it.each(['disabled', 'missing_enabled', 'expired', 'too_short', 'common_name', 'duplicate_identity', 'missing', 'secret', 'rotation_overlap', 'unknown_field'])('rejects service token %s', kind => { const f = fixture(), t = f.serviceTokens.result[0]; if (kind === 'disabled') t.enabled = false; if (kind === 'missing_enabled') delete t.enabled; if (kind === 'expired') t.expires_at = new Date(Date.now() - 1).toISOString(); if (kind === 'too_short') t.expires_at = new Date(Date.now() + 1000).toISOString(); if (kind === 'common_name') t.client_id = H('other').slice(0, 32) + '.access'; if (kind === 'duplicate_identity') t.client_id = f.serviceTokens.result[1].client_id; if (kind === 'missing') f.serviceTokens = list(f.serviceTokens.result.slice(1)); if (kind === 'secret') t.client_secret = 'must-not-render'; if (kind === 'rotation_overlap') t.previous_client_secret_expires_at = new Date(Date.now() + DAY).toISOString(); if (kind === 'unknown_field') t.future_permission = true; expect(() => validateRehearsalAccessReadback(f)).toThrow('rehearsal_access_readback_refused'); });
  it.each(['missing_key', 'wrong_key', 'private_jwk', 'wrong_certificate', 'expired_certificate', 'future_certificate', 'missing_cert', 'wrong_current', 'extra_jwks_field'])('rejects JWKS %s', kind => { const f = fixture(); if (kind === 'missing_key') f.jwks.keys = []; if (kind === 'wrong_key') f.jwks.keys[0].n = otherRsa.publicKey.export({ format: 'jwk' }).n; if (kind === 'private_jwk') f.jwks.keys[0].d = 'private'; if (kind === 'wrong_certificate') f.jwks.public_certs[0].cert = otherCert; if (kind === 'expired_certificate') f.jwks.public_certs[0].cert = certificate(rsa, Date.now() - 2 * DAY, Date.now() - DAY); if (kind === 'future_certificate') f.jwks.public_certs[0].cert = certificate(rsa, Date.now() + DAY, Date.now() + 2 * DAY); if (kind === 'missing_cert') f.jwks.public_certs = []; if (kind === 'wrong_current') f.jwks.public_cert.kid = 'unknown'; if (kind === 'extra_jwks_field') f.jwks.redirect = 'https://other.example.com'; expect(() => validateRehearsalAccessReadback(f)).toThrow(); });
  it('rejects credential-bearing/getter inputs without rendering or executing them', () => { const f = fixture(), getter = vi.fn(() => 'secret'); Object.defineProperty(f.organization.result, 'client_secret', { get: getter, enumerable: true }); expect(() => validateRehearsalAccessReadback(f)).toThrow('rehearsal_access_readback_refused'); expect(getter).not.toHaveBeenCalled(); });
  it('contains no network, credential, mutation or secret creation capability', () => { const source = readFileSync(new URL('../../scripts/lib/follow-up-rehearsal-access-readback.mjs', import.meta.url), 'utf8'); expect(source).not.toMatch(/\bfetch\s*\(|writeFile|createPrivateKey|generateKey|child_process|process\.env|console\./); });
});
