import { afterAll, beforeAll, describe, expect, it, vi } from "vitest";
import { createHash, generateKeyPairSync, sign, verify } from "node:crypto";
import { readFileSync, mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";
import { Miniflare, convertV4MiniflareOptions } from "miniflare";
import { createFollowUpEvidenceCaptureBucket, createFollowUpEvidenceRegistryAdapter, createFollowUpEvidenceWitnessAdapter, createFollowUpCurrentFloorIssuer, followUpFloorSourceSigningBytes, followUpWitnessSigningBytes, FOLLOW_UP_REGISTRY_SCHEMA_DIGEST, FOLLOW_UP_REGISTRY_SCHEMA, FOLLOW_UP_STORAGE_ADAPTER_FLAGS } from "../../scripts/lib/follow-up-evidence-storage-adapters.mjs";
import { followUpCurrentFloorSigningBytes } from "../../scripts/lib/follow-up-evidence-admission-gate.mjs";

// All Worker code below is a synthetic in-memory test entrypoint, never a shipped
// route/configuration. It runs the real unchanged gate/capture + new adapters in
// workerd with real SQLite DO transactions/sync and native R2 conditional methods.
// Local restart persistence is NOT provider replication/PITR/authentication proof.
const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
const TIME = 1800000000000, DAY = 86400000;
const canonical = v => Array.isArray(v) ? `[${v.map(canonical).join(",")}]` : v && typeof v === "object" ? `{${Object.keys(v).sort().map(k => `${JSON.stringify(k)}:${canonical(v[k])}`).join(",")}}` : JSON.stringify(v);
const hash = s => createHash("sha256").update(s).digest("hex"), id = s => "id_" + hash(s);
const keys = Object.fromEntries(["admission", "capture", "floor", "receipt", "witness", "source"].map(role => { const k = generateKeyPairSync("ed25519"); return [role, { privateKey: k.privateKey.export({ format: "pem", type: "pkcs8" }), publicKey: k.publicKey.export({ format: "pem", type: "spki" }) }]; }));
const WORKER = String.raw`
import { createHash,createPrivateKey,createPublicKey,sign } from "node:crypto";
import { createFollowUpEvidenceRegistryAdapter,createFollowUpEvidenceWitnessAdapter,createFollowUpEvidenceCaptureBucket,createFollowUpCurrentFloorIssuer,FOLLOW_UP_REGISTRY_SCHEMA,FOLLOW_UP_REGISTRY_SCHEMA_DIGEST,followUpWitnessSigningBytes,followUpFloorSourceSigningBytes } from "./scripts/lib/follow-up-evidence-storage-adapters.mjs";
import { createFollowUpEvidenceAdmissionGate,followUpAdmissionSigningBytes } from "./scripts/lib/follow-up-evidence-admission-gate.mjs";
import { followUpEvidenceIntentSigningBytes } from "./scripts/lib/follow-up-evidence-capture-integration.mjs";
const TIME=1800000000000,DAY=86400000;
const canonical=v=>Array.isArray(v)?"["+v.map(canonical).join(",")+"]":v&&typeof v==="object"?"{"+Object.keys(v).sort().map(k=>JSON.stringify(k)+":"+canonical(v[k])).join(",")+"}":JSON.stringify(v);
const hash=x=>createHash("sha256").update(x).digest("hex"),id=x=>"id_"+hash(x);
const head=c=>({scopeDigest:c.scopeDigest,epoch:c.epoch,generation:c.generation,sequence:c.sequence,digest:c.headDigest});
function fixture(name,keys){
 const scope={accountId:id("account/"+name),targetId:id("target"),actionScopeDigest:hash("action"),environment:"synthetic",sinkId:id("sink"),registryId:id("registry/"+name),schemaDigest:FOLLOW_UP_REGISTRY_SCHEMA_DIGEST,sourceRevision:"a".repeat(40),actionDigest:hash("action revision"),handlerDigest:hash("handler"),epoch:id("epoch"),generation:1,issuerReleaseDigest:hash("issuer"),policyVersion:"follow-up-retention-policy.v1"};
 const origin={sourceId:id("source"),sequence:10,originalAt:TIME-1000,approvedAt:TIME,dispatchUntil:TIME+60000},businessKey=id(canonical({accountId:scope.accountId,targetId:scope.targetId,actionScopeDigest:scope.actionScopeDigest,environment:scope.environment,sourceId:origin.sourceId,sequence:origin.sequence}));
 const a={version:"follow-up-admission.v1",scope,origin,businessKey,aliasSetDigest:hash("all aliases"),replayHorizonUntil:TIME+100*DAY,retentionUntil:TIME+DAY,parentDeadline:TIME+DAY,deletionDeadline:null,issuedAt:TIME,issuerSequence:10,quotas:{metadataBytes:24000,chunks:16,rpcs:64}};
 const intent={version:"follow-up-capture-intent.v1",operationId:businessKey,actionDigest:scope.actionDigest,sourceRevision:scope.sourceRevision,sinkId:scope.sinkId,environment:scope.environment,originalAt:origin.originalAt,issuedAt:TIME,expiresAt:origin.dispatchUntil,retentionUntil:a.retentionUntil,parentDeadline:a.parentDeadline};
 const signedCapture={intent,keyId:id("capture"),signature:sign(null,followUpEvidenceIntentSigningBytes(intent),keys.capture.privateKey).toString("base64")};a.captureIntentDigest=hash(followUpEvidenceIntentSigningBytes(intent));
 const request={admission:a,capture:signedCapture,keyId:id("admission"),signature:sign(null,followUpAdmissionSigningBytes(a),keys.admission.privateKey).toString("base64")};
 const scopeDigest=hash(canonical(scope)),control={version:"follow-up-admission-control.v1",scopeDigest,epoch:scope.epoch,generation:scope.generation,mode:"active",sequence:0,headDigest:hash("genesis/"+name),pending:null};return {scope,scopeDigest,a,request,control};
}
export class SyntheticRegistry {
 constructor(ctx,env){this.ctx=ctx;this.env=env;this.keys=Object.fromEntries(Object.entries(JSON.parse(env.KEYS)).map(([k,v])=>[k,{privateKey:createPrivateKey(v.privateKey),publicKey:createPublicKey(v.publicKey)}]));}
 async fetch(request){const input=await request.json(),f=fixture(input.name,this.keys),ctx=this.ctx,env=this.env;let time=input.time??TIME,revoked=false;const metrics={sql:0,transaction:0,sync:0,get:0,put:0,authorization:0,source:0,maxBindings:0,maxSqlBytes:0};
 const grant=async q=>{metrics.authorization++;if(input.fault==="deny"||revoked||input.fault==="deny_write"&&q.purpose==="write")throw Error("synthetic access denied");return {version:"follow-up-storage-access.v1",scopeDigest:q.scopeDigest,resource:q.resource,purpose:q.purpose,nonce:q.nonce,issuedAt:time,expiresAt:time+30000,retentionUntil:TIME+89*DAY};};
 const storage={sql:{exec(sql,...params){metrics.sql++;metrics.maxBindings=Math.max(metrics.maxBindings,params.length);metrics.maxSqlBytes=Math.max(metrics.maxSqlBytes,Buffer.byteLength(sql));return ctx.storage.sql.exec(sql,...params);}},transactionSync(fn){metrics.transaction++;const out=ctx.storage.transactionSync(()=>{const r=fn();if(input.fault==="rollback")throw Error("synthetic rollback");return r;});if(input.fault==="lost_transaction_ack")throw Error("synthetic lost ack");return out;},async sync(){metrics.sync++;await ctx.storage.sync();if(input.fault==="sync_revoked")revoked=true;if(input.fault==="sync_lost")throw Error("synthetic lost sync ack");}};
 const bucket={async get(key){metrics.get++;const object=await env.EVIDENCE.get(key);if(input.fault==="claim_expiry"&&key.endsWith("/claim"))time=f.a.origin.dispatchUntil;return object;},async put(key,text,options){metrics.put++;const ack=await env.EVIDENCE.put(key,text,options);if(input.fault==="witness_lost"&&key.includes("/transition/"))throw Error("synthetic lost witness ack");return ack;}};
 const common={scope:f.scope,authorize:grant,clock:()=>time,timeoutMs:1000},keyring=role=>[{keyId:id(role),publicKey:this.keys[role].publicKey}],signer=role=>({keyId:id(role),privateKey:this.keys[role].privateKey});
 const registry=createFollowUpEvidenceRegistryAdapter({...common,storage}),witness=createFollowUpEvidenceWitnessAdapter({...common,bucket,signer:signer("witness"),verificationKeys:keyring("witness")});
 const currentFloor=createFollowUpCurrentFloorIssuer({scope:f.scope,clock:()=>time,timeoutMs:1000,sourceKeys:keyring("source"),signer:signer("floor"),trustedSource:{read:async q=>{metrics.source++;const now=time,body={version:"follow-up-floor-source.v1",challengeDigest:hash("amari/follow-up-floor-challenge/v1\n"+canonical(q)),scopeDigest:f.scopeDigest,businessKey:f.a.businessKey,admissionDigest:hash(followUpAdmissionSigningBytes(f.a)),origin:f.a.origin,governance:{epoch:f.scope.epoch,generation:1,issuerReleaseDigest:f.scope.issuerReleaseDigest,minimumOriginSequence:1,state:"active",observedAt:now,expiresAt:now+30000},suppression:{aliasSetDigest:f.a.aliasSetDigest,replayHorizonUntil:f.a.replayHorizonUntil,disposition:input.fault==="suppressed"?"suppressed":"clear",observedAt:now,expiresAt:now+30000},observedAt:now,expiresAt:now+30000};if(input.fault==="old_floor")body.governance.generation=0+2;if(input.fault==="old_origin")body.origin={...body.origin,sequence:11};return {body,keyId:id("source"),signature:sign(null,followUpFloorSourceSigningBytes(body),thisKeys(input.fault,this.keys)).toString("base64")};}}});
 const captureBucket=createFollowUpEvidenceCaptureBucket({...common,bucket,operationId:f.a.businessKey,originalAt:f.a.origin.originalAt,retentionUntil:f.a.retentionUntil});
 const gate=createFollowUpEvidenceAdmissionGate({scope:f.scope,admissionKeys:keyring("admission"),floorKeys:keyring("floor"),registry,currentFloor,witness,capture:{bucket:captureBucket,intentKeys:keyring("capture"),receiptKeys:keyring("receipt"),receiptSigner:signer("receipt")},clock:()=>time,waitMs:1000,operationMs:10000,executeAction:i=>{ctx.storage.sql.exec("INSERT INTO synthetic_effects(value) VALUES(1)").toArray();if(input.fault==="effect_lost")throw Error("synthetic unknown effect");return {version:"follow-up-capture-metadata.v1",operationId:i.operationId,actionDigest:i.actionDigest,observedAt:time,outcome:"acknowledged",readback:"matches",statementCount:1,rowsRead:0,rowsWritten:1,evidenceDigests:[],reasonCodes:[]};}});
 let result;
 try{
  if(input.op==="seed"||input.op==="schema_only"){
   for(const sql of FOLLOW_UP_REGISTRY_SCHEMA)ctx.storage.sql.exec(sql).toArray();ctx.storage.sql.exec("CREATE TABLE synthetic_effects(value INTEGER NOT NULL)").toArray();
   if(input.op==="seed"){ctx.storage.sql.exec("INSERT INTO fue_registry_control VALUES(1,?,?,?)",f.scopeDigest,TIME+89*DAY,canonical(f.control)).toArray();const body={version:"follow-up-storage-witness.v1",kind:"head",scopeDigest:f.scopeDigest,createdAt:TIME,retentionUntil:TIME+89*DAY,payload:head(f.control)};await env.EVIDENCE.put("follow-up-admission-witness/v1/"+f.scopeDigest+"/head",canonical({body,keyId:id("witness"),signature:sign(null,followUpWitnessSigningBytes(body),this.keys.witness.privateKey).toString("base64")}),{onlyIf:{etagDoesNotMatch:"*"}});}await ctx.storage.sync();result={seeded:true};
  }else if(input.op==="admit")result=await gate.admit(f.request);
  else if(input.op==="execute")result=await gate.executeAdmitted(f.request);
  else if(input.op==="status")result=await gate.readStatus(f.request);
  else if(input.op==="capture")result=await gate.readCapture(f.request);
  else if(input.op==="confirm_latest"){const r=ctx.storage.sql.exec("SELECT transaction_id FROM fue_registry_receipts ORDER BY rowid DESC LIMIT 1").toArray()[0];result=await registry.confirm(r.transaction_id);}
  else if(input.op==="inspect"){result={control:ctx.storage.sql.exec("SELECT data,retention_until FROM fue_registry_control").toArray(),entries:ctx.storage.sql.exec("SELECT data FROM fue_registry_entries").toArray(),receipts:ctx.storage.sql.exec("SELECT transaction_id,data,retention_until FROM fue_registry_receipts").toArray(),effects:ctx.storage.sql.exec("SELECT count(*) AS n FROM synthetic_effects").toArray()[0].n};}
  else if(input.op==="tamper_head"){const key="follow-up-admission-witness/v1/"+f.scopeDigest+"/head",raw=JSON.parse(await (await env.EVIDENCE.get(key)).text());raw.body.payload.sequence++;await env.EVIDENCE.put(key,canonical(raw));result={tampered:true};}
  else if(input.op==="delete_head"){await env.EVIDENCE.delete("follow-up-admission-witness/v1/"+f.scopeDigest+"/head");result={deleted:true};}
  else if(input.op==="extra_schema"){ctx.storage.sql.exec("CREATE INDEX synthetic_rogue ON fue_registry_entries(retention_until)").toArray();result={changed:true};}
  else if(input.op==="hostile_updater"){let evaluated=0;try{await registry.transact(f.a.businessKey,s=>{const candidate={control:s.control,entry:s.entry};Object.defineProperty(candidate,"then",{enumerable:true,get(){evaluated++;return undefined;}});return candidate;});result={unexpected:true};}catch{result={refused:true,evaluated};}}
  else if(input.op==="direct_replace"){const old=ctx.storage.sql.exec("SELECT * FROM fue_registry_control").toArray()[0];ctx.storage.sql.exec("INSERT OR REPLACE INTO fue_registry_control VALUES(?,?,?,?)",old.id,old.scope_digest,old.retention_until,old.data).toArray();result={unexpected:true};}
  else if(input.op==="native_cas"){const key="synthetic-cas/"+input.name,a=await env.EVIDENCE.put(key,"a",{onlyIf:{etagDoesNotMatch:"*"}}),duplicate=await env.EVIDENCE.put(key,"b",{onlyIf:{etagDoesNotMatch:"*"}}),read=await env.EVIDENCE.get(key),bad=await env.EVIDENCE.put(key,"c",{onlyIf:{etagMatches:hash("a")}}),good=await env.EVIDENCE.put(key,"d",{onlyIf:{etagMatches:read.etag}});result={duplicate,bad,created:a.etag,read:read.etag,good:good.etag,text:await (await env.EVIDENCE.get(key)).text()};}
  else throw Error("unknown synthetic operation");
 }catch(e){result={error:e.message};}
 return Response.json({result,metrics});
 }
}
function thisKeys(fault,keys){return fault==="forged_source"?keys.witness.privateKey:keys.source.privateKey;}
export default {async fetch(request,env){const payload=await request.json();return env.REGISTRY.get(env.REGISTRY.idFromName(payload.name)).fetch(new Request("https://synthetic.invalid/",{method:"POST",body:JSON.stringify(payload)}));}};
`;

let mf, script, sequence = 0, outbound = 0;
const dirs = [];
function options(persist) { return { ...convertV4MiniflareOptions({ name: "synthetic-adapter", modules: true, script, compatibilityDate: "2026-08-20", compatibilityFlags: ["nodejs_compat"], host: "127.0.0.1", port: 0, bindings: { KEYS: JSON.stringify(keys) }, durableObjects: { REGISTRY: { className: "SyntheticRegistry", useSQLite: true } }, r2Buckets: ["EVIDENCE"], outboundService: () => { outbound++; return new Response("external I/O forbidden", { status: 403 }); } }), ...(persist ? { resourcePersistencePath: persist } : {}) }; }
async function run(name, op, extra = {}, instance = mf) { const res = await instance.dispatchFetch("http://localhost/", { method: "POST", body: JSON.stringify({ name, op, ...extra }) }); expect(res.status).toBe(200); return res.json(); }
async function seeded() { const name = "case-" + ++sequence; expect((await run(name, "seed")).result.seeded).toBe(true); return name; }
beforeAll(async () => { script = (await build({ stdin: { contents: WORKER, resolveDir: ROOT, sourcefile: "synthetic-adapter-worker.mjs" }, bundle: true, write: false, format: "esm", platform: "neutral", external: ["node:*"], target: "es2022" })).outputFiles[0].text; mf = new Miniflare(options()); await mf.ready; }, 30000);
afterAll(async () => { await mf?.dispose(); for (const dir of dirs) rmSync(dir, { recursive: true, force: true }); expect(outbound).toBe(0); }, 30000);

describe("actual local workerd DO/R2 adapters", () => {
  it("requires externally provisioned exact schema AND a positive control, with zero bootstrap writes", async () => {
    const name = "absent-" + ++sequence, a = await run(name, "admit"); expect(a.result.status).toBe("refused"); expect(a.metrics).toMatchObject({ transaction: 0, put: 0 });
    const empty = "empty-" + ++sequence; await run(empty, "schema_only"); const b = await run(empty, "admit"); expect(b.result.status).toBe("refused"); expect(b.metrics).toMatchObject({ transaction: 0, put: 0 });
  });
  it("composes the frozen gate/capture with real transactions, sync receipts and signed native R2 witnesses", async () => {
    const name = await seeded(), a = await run(name, "admit"); expect(a.result.status).toBe("admitted"); expect(a.metrics.sql).toBe(15); expect(a.metrics).toMatchObject({ transaction: 2, sync: 2, get: 7, put: 2, source: 1, authorization: 23 });
    const e = await run(name, "execute"); expect(e.result).toMatchObject({ status: "captured", actionAttempted: true, consumption: "confirmed", metadataCaptured: true, pendingBarrier: true }); expect(e.metrics.sql).toBe(19); expect(e.metrics).toMatchObject({ transaction: 2, sync: 2, get: 13, put: 5, source: 2, authorization: 52 }); expect(e.metrics.maxBindings).toBeLessThanOrEqual(100); expect(e.metrics.maxSqlBytes).toBeLessThanOrEqual(100000); expect(e.metrics.get + e.metrics.put + e.metrics.source).toBeLessThanOrEqual(64);
    for (const [k, v] of Object.entries(FOLLOW_UP_STORAGE_ADAPTER_FLAGS)) expect(e.result[k]).toBe(v);
    const state = (await run(name, "inspect")).result; expect(state.effects).toBe(1); expect(state.receipts).toHaveLength(4); expect(JSON.parse(state.entries[0].data).status).toBe("CONSUMED"); expect(state.control[0].retention_until).toBe(TIME + DAY);
    const again = await run(name, "execute"); expect(again.result).toMatchObject({ actionAttempted: false, reasonCode: "already_consumed" }); expect((await run(name, "inspect")).result.effects).toBe(1);
  });
  it("native create-if-absent is null on conflict and CAS uses an actual opaque ETag, not SHA256", async () => { const r = (await run("cas-" + ++sequence, "native_cas")).result; expect(r).toMatchObject({ duplicate: null, bad: null, text: "d" }); expect(r.created).toBe(r.read); expect(r.read).not.toBe(hash("a")); expect(r.good).not.toBe(r.read); });
  it("concurrent fresh adapters consume at most one invocation across the real DO scope", async () => { const name = await seeded(); await run(name, "admit"); const outcomes = await Promise.all([run(name, "execute"), run(name, "execute")]); expect(outcomes.filter(x => x.result.actionAttempted)).toHaveLength(1); expect((await run(name, "inspect")).result.effects).toBe(1); });
  it.each(["lost_transaction_ack", "sync_lost", "witness_lost"])("%s after admission preserves consumed state and never dispatches/retries", async fault => { const name = await seeded(); await run(name, "admit"); const r = await run(name, "execute", { fault }); expect(r.result.actionAttempted).toBe(false); const s = (await run(name, "inspect")).result; expect(JSON.parse(s.entries[0].data).status).toBe("CONSUMED"); expect(s.effects).toBe(0); expect((await run(name, "execute")).result.actionAttempted).toBe(false); });
  it("a synchronous transaction exception rolls back control, entry AND receipt", async () => { const name = await seeded(); const before = (await run(name, "inspect")).result; await run(name, "admit", { fault: "rollback" }); expect((await run(name, "inspect")).result).toEqual(before); });
  it("rejects an updater result accessor without invoking it or persisting any row", async () => { const name = await seeded(), before = (await run(name, "inspect")).result; expect((await run(name, "hostile_updater")).result).toEqual({ refused: true, evaluated: 0 }); expect((await run(name, "inspect")).result).toEqual(before); });
  it.each(["forged_source", "old_origin", "old_floor", "suppressed"])("refuses %s without registry mutation or action", async fault => { const name = await seeded(); const r = await run(name, "admit", { fault }); expect(r.result.status).toBe("refused"); expect(r.metrics).toMatchObject({ transaction: 0, put: 0 }); });
  it("expiry during native capture claim read never invokes the effect", async () => { const name = await seeded(); await run(name, "admit"); const r = await run(name, "execute", { fault: "claim_expiry" }); expect(r.result).toMatchObject({ consumption: "confirmed", actionAttempted: false }); expect((await run(name, "inspect")).result.effects).toBe(0); });
  it("effect then lost response is captured as unknown without a renewed action", async () => { const name = await seeded(); await run(name, "admit"); const r = await run(name, "execute", { fault: "effect_lost" }); expect(r.result).toMatchObject({ actionAttempted: true, actionReport: "unknown", metadataCaptured: true }); expect((await run(name, "execute")).result.actionAttempted).toBe(false); expect((await run(name, "inspect")).result.effects).toBe(1); });
  it("read-only status/capture never write, and present access revocation blocks object reads", async () => { const name = await seeded(); await run(name, "admit"); await run(name, "execute"); const s = await run(name, "status"), c = await run(name, "capture"); expect(s.result.status).toBe("observed"); expect(c.result.metadataCaptured).toBe(true); for (const r of [s, c]) expect(r.metrics).toMatchObject({ transaction: 0, put: 0 }); const denied = await run(name, "capture", { fault: "deny" }); expect(denied.result.metadataCaptured).toBe(false); expect(denied.metrics.get).toBe(0); });
  it("confirm reauthorizes after real sync and never exports an expired receipt", async () => { const name = await seeded(); await run(name, "admit"); expect((await run(name, "confirm_latest", { fault: "sync_revoked" })).result.error).toBe("storage_adapter_unavailable"); expect((await run(name, "confirm_latest", { time: TIME + DAY })).result.error).toBe("storage_adapter_unavailable"); });
  it.each(["tamper_head", "delete_head", "extra_schema"])("%s is a gap, not permission to bootstrap or dispatch", async op => { const name = await seeded(); await run(name, "admit"); await run(name, op); const r = await run(name, "execute"); expect(r.result.actionAttempted).toBe(false); expect(r.metrics).toMatchObject({ transaction: 0, put: 0 }); });
  it("direct INSERT OR REPLACE cannot erase an existing control", async () => { const name = await seeded(); const before = (await run(name, "inspect")).result; expect((await run(name, "direct_replace")).result.error).toContain("immutable"); expect((await run(name, "inspect")).result).toEqual(before); });
  it("real persisted receipts survive workerd disposal and reopening without promise maps", async () => {
    const dir = mkdtempSync(join(tmpdir(), "follow-up-adapter-platform-")); dirs.push(dir); const name = "restart", first = new Miniflare(options(dir)); await first.ready;
    try { await run(name, "seed", {}, first); expect((await run(name, "admit", {}, first)).result.status).toBe("admitted"); } finally { await first.dispose(); }
    const reopened = new Miniflare(options(dir)); await reopened.ready; try { const receipt = (await run(name, "confirm_latest", {}, reopened)).result; expect(receipt).toHaveProperty("snapshot.entry.status", "ADMITTED"); expect((await run(name, "execute", {}, reopened)).result.actionAttempted).toBe(true); expect((await run(name, "inspect", {}, reopened)).result.effects).toBe(1); } finally { await reopened.dispose(); }
    const consumed = new Miniflare(options(dir)); await consumed.ready; try { expect((await run(name, "confirm_latest", {}, consumed)).result.snapshot.entry.status).toBe("CONSUMED"); expect((await run(name, "execute", {}, consumed)).result).toMatchObject({ actionAttempted: false, reasonCode: "already_consumed" }); expect((await run(name, "inspect", {}, consumed)).result.effects).toBe(1); } finally { await consumed.dispose(); }
  }, 30000);
});

function unit() {
  const state = { time: TIME, deny: false }, pair = generateKeyPairSync("ed25519"), sourcePair = generateKeyPairSync("ed25519"), floorPair = generateKeyPairSync("ed25519");
  const scope = { accountId: id("unit account"), targetId: id("unit target"), actionScopeDigest: hash("unit action"), environment: "synthetic", sinkId: id("unit sink"), registryId: id("unit registry"), schemaDigest: FOLLOW_UP_REGISTRY_SCHEMA_DIGEST, sourceRevision: "a".repeat(40), actionDigest: hash("action revision"), handlerDigest: hash("handler"), epoch: id("epoch"), generation: 1, issuerReleaseDigest: hash("issuer"), policyVersion: "follow-up-retention-policy.v1" }, scopeDigest = hash(canonical(scope));
  const authorize = vi.fn(async q => { if (state.deny) throw Error("SECRET current grant denied"); return { version: "follow-up-storage-access.v1", scopeDigest: q.scopeDigest, resource: q.resource, purpose: q.purpose, nonce: q.nonce, issuedAt: state.time, expiresAt: state.time + 30000, retentionUntil: TIME + 89 * DAY }; });
  const common = { scope, authorize, clock: () => state.time, timeoutMs: 100 }, operationId = id("unit operation"), prefix = `follow-up-evidence-capture/v1/${operationId}/`, objects = new Map();
  const bucket = { get: vi.fn(async key => { const text = objects.get(key); if (text === undefined) return null; const bytes = Buffer.from(text); return { etag: "opaque-native-etag", size: bytes.length, body: new ReadableStream({ start(c) { c.enqueue(bytes); c.close(); } }) }; }), put: vi.fn(async (key, text, options) => { if (options.onlyIf.etagDoesNotMatch === "*" && objects.has(key)) return null; objects.set(key, text); return { etag: "opaque-native-etag" }; }) };
  const captureConfig = { ...common, bucket, operationId, originalAt: TIME - 1000, retentionUntil: TIME + DAY };
  const witnessConfig = { ...common, bucket, signer: { keyId: id("witness"), privateKey: pair.privateKey }, verificationKeys: [{ keyId: id("witness"), publicKey: pair.publicKey }] };
  const origin = { sourceId: id("source"), sequence: 10, originalAt: TIME - 1000, approvedAt: TIME, dispatchUntil: TIME + 60000 }, businessKey = id(canonical({ accountId: scope.accountId, targetId: scope.targetId, actionScopeDigest: scope.actionScopeDigest, environment: scope.environment, sourceId: origin.sourceId, sequence: origin.sequence }));
  const challenge = { version: "follow-up-floor-challenge.v1", nonce: hash("fresh challenge"), scopeDigest, businessKey, admissionDigest: hash("admission"), originDigest: hash(canonical(origin)), expectedSequence: 1, expectedHeadDigest: hash("head") };
  const proof = q => ({ version: "follow-up-floor-source.v1", challengeDigest: hash("amari/follow-up-floor-challenge/v1\n" + canonical(q)), scopeDigest, businessKey, admissionDigest: challenge.admissionDigest, origin, governance: { epoch: scope.epoch, generation: scope.generation, issuerReleaseDigest: scope.issuerReleaseDigest, minimumOriginSequence: 1, state: "active", observedAt: state.time, expiresAt: state.time + 30000 }, suppression: { aliasSetDigest: hash("all aliases"), replayHorizonUntil: TIME + 100 * DAY, disposition: "clear", observedAt: state.time, expiresAt: state.time + 30000 }, observedAt: state.time, expiresAt: state.time + 30000 });
  const envelope = body => ({ body, keyId: id("source"), signature: sign(null, followUpFloorSourceSigningBytes(body), sourcePair.privateKey).toString("base64") });
  const issuerConfig = { scope, clock: common.clock, timeoutMs: 100, trustedSource: { read: vi.fn(async q => envelope(proof(q))) }, sourceKeys: [{ keyId: id("source"), publicKey: sourcePair.publicKey }], signer: { keyId: id("floor"), privateKey: floorPair.privateKey } };
  return { state, pair, sourcePair, floorPair, scope, scopeDigest, common, authorize, bucket, objects, prefix, operationId, captureConfig, witnessConfig, issuerConfig, challenge, proof, envelope };
}
const event = f => ({ version: "follow-up-admission-transition.v1", scopeDigest: f.scopeDigest, epoch: f.scope.epoch, generation: f.scope.generation, sequence: 1, previousDigest: hash("genesis"), kind: "admit", businessKey: id("business"), admissionDigest: hash("admission"), originDigest: hash("origin"), at: TIME, retentionUntil: TIME + DAY, previousEntryDigest: null, entryDigest: hash("entry") });
const headBody = f => ({ version: "follow-up-storage-witness.v1", kind: "head", scopeDigest: f.scopeDigest, createdAt: TIME, retentionUntil: TIME + DAY, payload: { scopeDigest: f.scopeDigest, epoch: f.scope.epoch, generation: f.scope.generation, sequence: 0, digest: hash("genesis") } });
function installHead(f, body = headBody(f), signatureKey = f.pair.privateKey) { const envelope = { body, keyId: id("witness"), signature: sign(null, followUpWitnessSigningBytes(body), signatureKey).toString("base64") }; f.objects.set(`follow-up-admission-witness/v1/${f.scopeDigest}/head`, canonical(envelope)); return body.payload; }

describe("bounded adapter authorization and hostile-boundary regressions", () => {
  it("binds the declared schema digest and never runs DDL in a constructor", () => { const f = unit(), exec = vi.fn(), storage = { sql: { exec }, transactionSync: fn => fn(), sync: async () => {} }; expect(() => createFollowUpEvidenceRegistryAdapter({ ...f.common, storage, scope: { ...f.scope, schemaDigest: hash("wrong") } })).toThrow("storage_adapter_unavailable"); createFollowUpEvidenceRegistryAdapter({ ...f.common, storage }); expect(exec).not.toHaveBeenCalled(); });
  it.each(["authorize", "clock", "timeoutMs"])("requires factory %s, not a request permission flag", field => { const f = unit(); delete f.captureConfig[field]; expect(() => createFollowUpEvidenceCaptureBucket(f.captureConfig)).toThrow(); expect(f.bucket.put).not.toHaveBeenCalled(); });
  it("rejects a mismatched witness signing pair before any R2 write", () => { const f = unit(); f.witnessConfig.signer.privateKey = generateKeyPairSync("ed25519").privateKey; expect(() => createFollowUpEvidenceWitnessAdapter(f.witnessConfig)).toThrow("storage_adapter_unavailable"); expect(f.bucket.put).not.toHaveBeenCalled(); });
  it("never writes a known-invalid 91-day transition or accepts a 91-day seed head", async () => { const f = unit(), e = { ...event(f), retentionUntil: TIME + 91 * DAY }; await expect(createFollowUpEvidenceWitnessAdapter(f.witnessConfig).putTransition(e)).rejects.toThrow("storage_adapter_unavailable"); expect(f.bucket.put).not.toHaveBeenCalled(); expect(() => followUpWitnessSigningBytes({ ...headBody(f), retentionUntil: TIME + 91 * DAY })).toThrow(); });
  it.each(["signature", "scope", "epoch", "expired"])("refuses signed-witness %s mismatch without repairing head", async kind => { const f = unit(), body = headBody(f); if (kind === "scope") body.payload.scopeDigest = hash("foreign"); if (kind === "epoch") body.payload.epoch = id("foreign"); installHead(f, body, kind === "signature" ? generateKeyPairSync("ed25519").privateKey : f.pair.privateKey); if (kind === "expired") f.state.time = body.retentionUntil; await expect(createFollowUpEvidenceWitnessAdapter(f.witnessConfig).readHead(f.scopeDigest)).rejects.toThrow("storage_adapter_unavailable"); expect(f.bucket.put).not.toHaveBeenCalled(); });
  it("requires an existing head and preserves the shortest original head deadline", async () => { const f = unit(), w = createFollowUpEvidenceWitnessAdapter(f.witnessConfig), first = headBody(f).payload, e = { ...event(f), retentionUntil: TIME + 600000 }, d = hash(canonical(e)); await expect(w.compareAndSwapHead(first, { ...first, sequence: 1, digest: d })).rejects.toThrow(); expect(f.bucket.put).not.toHaveBeenCalled(); installHead(f); await w.putTransition(e); expect(await w.compareAndSwapHead(first, { ...first, sequence: 1, digest: d })).toEqual({ head: { ...first, sequence: 1, digest: d } }); const raw = JSON.parse(f.objects.get(`follow-up-admission-witness/v1/${f.scopeDigest}/head`)); expect(raw.body).toMatchObject({ createdAt: TIME, retentionUntil: TIME + 600000 }); expect(f.bucket.put.mock.calls.at(-1)[2]).toEqual({ onlyIf: { etagMatches: "opaque-native-etag" } }); });
  it("expires after witness write/readback without declaring a successful acknowledgement", async () => { const f = unit(), put = f.bucket.put; f.bucket.put = vi.fn(async (...args) => { const result = await put(...args); f.state.time = TIME + DAY; return result; }); await expect(createFollowUpEvidenceWitnessAdapter(f.witnessConfig).putTransition(event(f))).rejects.toThrow(); expect(f.objects.size).toBe(1); });
  it.each(["foreign-operation/claim", "claim?x=1", "chunk-16", "../head", "manifest/extra"])("rejects non-allowlisted capture suffix %s before storage", suffix => { const f = unit(), c = createFollowUpEvidenceCaptureBucket(f.captureConfig); expect(() => c.get(f.prefix + suffix)).toThrow(); expect(f.bucket.get).not.toHaveBeenCalled(); });
  it("exposes no native list/delete/overwrite and requires create-only writes", async () => { const f = unit(), c = createFollowUpEvidenceCaptureBucket(f.captureConfig); expect(Object.keys(c).sort()).toEqual(["get", "put"]); expect(() => c.put(f.prefix + "claim", "x", { onlyIf: { etagMatches: "etag" } })).toThrow(); expect(() => c.put(f.prefix + "chunk-0", "x".repeat(4097), { onlyIf: { etagDoesNotMatch: "*" } })).toThrow(); f.state.deny = true; await expect(c.put(f.prefix + "claim", "x", { onlyIf: { etagDoesNotMatch: "*" } })).rejects.toThrow(); expect(f.bucket.put).not.toHaveBeenCalled(); });
  it.each([false, true])("revocation during native get rejects even a %s present object before metadata export", async present => { const f = unit(), cancelled = vi.fn(); f.bucket.get = vi.fn(async () => { f.state.deny = true; return present ? { etag: "etag", size: 1, body: { cancel: cancelled } } : null; }); await expect(createFollowUpEvidenceCaptureBucket(f.captureConfig).get(f.prefix + "claim")).rejects.toThrow("storage_adapter_unavailable"); expect(f.authorize).toHaveBeenCalledTimes(2); expect(cancelled).toHaveBeenCalledTimes(present ? 1 : 0); });
  it.each(["size", "etag", "expiry"])("cancels native body when post-get %s validation fails", async kind => { const f = unit(), cancelled = vi.fn(); f.bucket.get = vi.fn(async () => { if (kind === "expiry") f.state.time = TIME + DAY; return { etag: kind === "etag" ? "" : "etag", size: kind === "size" ? 9000 : 1, body: { cancel: cancelled, getReader() { throw Error("must not acquire"); } } }; }); await expect(createFollowUpEvidenceCaptureBucket(f.captureConfig).get(f.prefix + "claim")).rejects.toThrow(); expect(cancelled).toHaveBeenCalledTimes(1); });
  it("rechecks present authorization between capture body chunks, not only at object get", async () => { const f = unit(), cancelled = vi.fn(), native = { read: vi.fn().mockResolvedValue({ done: false, value: Uint8Array.of(1) }), cancel: cancelled, releaseLock() {} }; f.bucket.get = vi.fn(async () => ({ size: 2, etag: "etag", body: { getReader: () => native } })); const object = await createFollowUpEvidenceCaptureBucket(f.captureConfig).get(f.prefix + "claim"), reader = object.body.getReader(); expect((await reader.read()).value).toEqual(Uint8Array.of(1)); f.state.deny = true; await expect(reader.read()).rejects.toThrow(); expect(native.read).toHaveBeenCalledTimes(1); expect(cancelled).toHaveBeenCalled(); });
  it("a hung native capture read is cancelled on timeout without waiting for cancel acknowledgement", async () => { const f = unit(), cancelled = vi.fn(() => new Promise(() => {})); f.captureConfig.timeoutMs = 10; f.bucket.get = vi.fn(async () => ({ size: 1, etag: "etag", body: { getReader: () => ({ read: () => new Promise(() => {}), cancel: cancelled, releaseLock() {} }) } })); const reader = (await createFollowUpEvidenceCaptureBucket(f.captureConfig).get(f.prefix + "claim")).body.getReader(); await expect(reader.read()).rejects.toThrow(); expect(cancelled).toHaveBeenCalled(); });
  it("late capture get never starts a reader after timeout and cancels its body", async () => { const f = unit(); f.captureConfig.timeoutMs = 10; let done; const cancelled = vi.fn(), acquire = vi.fn(); f.bucket.get = vi.fn(() => new Promise(resolve => { done = resolve; })); const result = createFollowUpEvidenceCaptureBucket(f.captureConfig).get(f.prefix + "claim"); await expect(result).rejects.toThrow(); done({ size: 1, etag: "etag", body: { getReader: acquire, cancel: cancelled } }); await new Promise(resolve => setTimeout(resolve, 2)); expect(acquire).not.toHaveBeenCalled(); expect(cancelled).toHaveBeenCalled(); });
  it("late native read cannot expose a chunk after its capability was timed out", async () => { const f = unit(); f.captureConfig.timeoutMs = 10; let done; const cancelled = vi.fn(); f.bucket.get = vi.fn(async () => ({ size: 1, etag: "etag", body: { getReader: () => ({ read: () => new Promise(resolve => { done = resolve; }), cancel: cancelled, releaseLock() {} }) } })); const reader = (await createFollowUpEvidenceCaptureBucket(f.captureConfig).get(f.prefix + "claim")).body.getReader(), promise = reader.read(); await expect(promise).rejects.toThrow(); done({ done: false, value: Uint8Array.of(1) }); await new Promise(resolve => setTimeout(resolve, 2)); await expect(reader.read()).rejects.toThrow(); expect(cancelled).toHaveBeenCalled(); });
  it("hanging witness-body reads are also cancelled by the adapter deadline", async () => { const f = unit(), cancelled = vi.fn(() => new Promise(() => {})); f.witnessConfig.timeoutMs = 10; f.bucket.get = vi.fn(async () => ({ size: 1, etag: "etag", body: { getReader: () => ({ read: () => new Promise(() => {}), cancel: cancelled, releaseLock() {} }) } })); await expect(createFollowUpEvidenceWitnessAdapter(f.witnessConfig).readHead(f.scopeDigest)).rejects.toThrow(); expect(cancelled).toHaveBeenCalled(); });
  it("enforces a finite native-body part bound without buffering arbitrary streams", async () => { const f = unit(), cancelled = vi.fn(); f.bucket.get = vi.fn(async () => ({ size: 100, etag: "etag", body: { getReader: () => ({ read: async () => ({ done: false, value: Uint8Array.of(1) }), cancel: cancelled, releaseLock() {} }) } })); const reader = (await createFollowUpEvidenceCaptureBucket(f.captureConfig).get(f.prefix + "claim")).body.getReader(); for (let i = 0; i < 32; i++) await reader.read(); await expect(reader.read()).rejects.toThrow(); expect(cancelled).toHaveBeenCalled(); });
  it("signs a fresh challenge-bound floor using only factory trusted-source proof", async () => { const f = unit(), out = await createFollowUpCurrentFloorIssuer(f.issuerConfig).read(f.challenge); expect(verify(null, followUpCurrentFloorSigningBytes(out.floor), f.floorPair.publicKey, Buffer.from(out.signature, "base64"))).toBe(true); expect(out.floor).toMatchObject({ issuedAt: TIME, expiresAt: TIME + 30000, eligibility: "clear", originDigest: f.challenge.originDigest }); expect(f.issuerConfig.trustedSource.read).toHaveBeenCalledOnce(); expect(Object.isFrozen(out)).toBe(true); });
  it("snapshots the issuer deadline budget at factory construction", async () => { const f = unit(), issuer = createFollowUpCurrentFloorIssuer(f.issuerConfig); f.issuerConfig.timeoutMs = 0; expect((await issuer.read(f.challenge)).floor.eligibility).toBe("clear"); });
  it.each(["challenge", "scope", "admission", "origin", "epoch", "generation", "release", "stale", "horizon", "signature", "key"])("does not issue a floor for %s proof mismatch", async kind => { const f = unit(); f.issuerConfig.trustedSource.read = async q => { const body = f.proof(q); if (kind === "challenge") body.challengeDigest = hash("other"); if (kind === "scope") body.scopeDigest = hash("other"); if (kind === "admission") body.admissionDigest = hash("other"); if (kind === "origin") body.origin = { ...body.origin, originalAt: TIME - 2000 }; if (kind === "epoch") body.governance.epoch = id("other"); if (kind === "generation") body.governance.generation++; if (kind === "release") body.governance.issuerReleaseDigest = hash("other"); if (kind === "stale") body.governance.observedAt = TIME - 1; if (kind === "horizon") body.suppression.replayHorizonUntil = TIME; let e; try { e = f.envelope(body); } catch { return { body, keyId: id("source"), signature: "A".repeat(86) + "==" }; } if (kind === "signature") e.signature = sign(null, followUpFloorSourceSigningBytes(body), f.pair.privateKey).toString("base64"); if (kind === "key") e.keyId = id("untrusted"); return e; }; await expect(createFollowUpCurrentFloorIssuer(f.issuerConfig).read(f.challenge)).rejects.toThrow("storage_adapter_unavailable"); });
  it("source proof that expires during await cannot mint a new window", async () => { const f = unit(); f.issuerConfig.trustedSource.read = async q => { const e = f.envelope(f.proof(q)); f.state.time += 30000; return e; }; await expect(createFollowUpCurrentFloorIssuer(f.issuerConfig).read(f.challenge)).rejects.toThrow(); });
  it("late source response after timeout never returns a certificate", async () => { const f = unit(); f.issuerConfig.timeoutMs = 10; let done; f.issuerConfig.trustedSource.read = q => new Promise(resolve => { done = () => resolve(f.envelope(f.proof(q))); }); const result = createFollowUpCurrentFloorIssuer(f.issuerConfig).read(f.challenge); await expect(result).rejects.toThrow(); done(); await new Promise(resolve => setTimeout(resolve, 2)); });
  it("snapshots challenges before await and rejects getters without evaluation", async () => { const f = unit(); let release; f.issuerConfig.trustedSource.read = q => new Promise(resolve => { release = () => resolve(f.envelope(f.proof(q))); }); const issuer = createFollowUpCurrentFloorIssuer(f.issuerConfig), original = { ...f.challenge }, pending = issuer.read(f.challenge); f.challenge.nonce = hash("caller mutation"); await Promise.resolve(); release(); expect((await pending).floor.challengeDigest).toBe(hash("amari/follow-up-floor-challenge/v1\n" + canonical(original))); const getter = vi.fn(); Object.defineProperty(f.challenge, "nonce", { get: getter, enumerable: true }); await expect(issuer.read(f.challenge)).rejects.toThrow(); expect(getter).not.toHaveBeenCalled(); });
  it("preserves frozen source bytes and provides no production transport or installer", () => { for (const [name, expected] of [["follow-up-evidence-admission-gate.mjs", "926aca9873050fcf704f0207d68f772f616ceca55b00a8408b6e93afde24a324"], ["follow-up-evidence-capture-integration.mjs", "80eb6ea3d916f5bdc5b934d87ba13ac46ace2013399bd628548e80841d557804"], ["follow-up-evidence-capture.mjs", "db7bae45b8364e5cdca541678f3949877e131db9a8a5ff9cf84e5af1628644f9"]]) expect(hash(readFileSync(join(ROOT, "scripts/lib", name)))).toBe(expected); const source = readFileSync(join(ROOT, "scripts/lib/follow-up-evidence-storage-adapters.mjs"), "utf8"); expect(/node:(?:fs|http|https|net|child_process)|\bfetch\s*\(|process\.|(?:bucket|storage|registry|witness)\.(?:delete|list)\s*\(|withExactBitwarden|BEGIN IMMEDIATE/.test(source)).toBe(false); expect(FOLLOW_UP_REGISTRY_SCHEMA).toHaveLength(12); });
});
