import { beforeAll, describe, expect, it, vi } from 'vitest';
import { createHash, generateKeyPairSync, sign } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { build } from 'esbuild';
import { GATEWAY_TARGET, GATEWAY_LIMITS, inspectGatewayDeploymentCandidate, gatewayDeploymentApprovalDigest, validateGatewayDeploymentApproval, deployGatewayRehearsal } from '../../scripts/follow-up-rehearsal-gateway-deploy.mjs';
import { DEPLOY_LIMITS, DEPLOY_TARGETS as TARGET, SHELL_SOURCE, deploymentApprovalDigest } from '../../scripts/follow-up-rehearsal-deploy.mjs';
import { HOST_RECORD_KEYS, inspectHostCandidate, hostApprovalSigningBytes, runRehearsalHost } from '../../scripts/follow-up-rehearsal-host.mjs';
import { VERSION, ACTION_DIGEST, canonical, encode, manifestSigningBytes } from '../../follow-up-rehearsal-worker/src/protocol.mjs';
import { FOLLOW_UP_REGISTRY_SCHEMA_DIGEST } from '../../scripts/lib/follow-up-evidence-storage-adapters.mjs';

const ROOT = fileURLToPath(new URL('../../', import.meta.url)), REV = 'a'.repeat(40), PRIOR = 'b'.repeat(40), ZONE = 'd'.repeat(32);
const hash = x => createHash('sha256').update(x).digest('hex'), id = x => 'id_' + hash(x), uuid = n => `00000000-0000-4000-8000-${String(n).padStart(12, '0')}`;
const roles = ['root', 'owner', 'operator', 'reader', 'admission', 'capture', 'floor', 'receipt', 'witness', 'source'];
const keys = Object.fromEntries(roles.map(r => [r, generateKeyPairSync('ed25519')]));
const pub = r => keys[r].publicKey.export({ type: 'spki', format: 'pem' }), fingerprint = r => hash(keys[r].publicKey.export({ type: 'spki', format: 'der' }));
const rsa = generateKeyPairSync('rsa', { modulusLength: 2048 }).publicKey.export({ format: 'jwk' });
let candidate, callerBytes;
function git(args) {
  if (args[0] === 'rev-parse') return REV;
  if (args[0] === 'status') return '';
  if (args[0] === 'remote') return 'https://github.com/Eben283/amarimethod-website.git';
  if (args[0] === 'ls-remote') return `${REV}\trefs/heads/main`;
  if (args[0] === 'show') return readFileSync(ROOT + args[1].slice(41));
  throw Error('unexpected synthetic Git read');
}
beforeAll(async () => {
  candidate = await inspectGatewayDeploymentCandidate({ git });
  const result = await build({ absWorkingDir: ROOT, entryPoints: ['follow-up-rehearsal-worker/src/caller.mjs'], bundle: true, write: false, format: 'esm', platform: 'neutral', target: 'es2022', external: ['node:crypto', 'cloudflare:workers'], logLevel: 'silent', minify: false, sourcemap: false });
  callerBytes = Buffer.from(result.outputFiles[0].contents); expect(hash(callerBytes)).toBe(candidate.artifact.bundles.find(b => b.role === 'caller').sha256);
});
function fixture() {
  const at = Date.now() - 10, day = 86400000, bundle = role => candidate.artifact.bundles.find(b => b.role === role).sha256;
  const scope = { accountId: id('account'), targetId: id('target'), actionScopeDigest: hash('counter'), environment: 'synthetic', sinkId: id('sink'), registryId: id('registry'), schemaDigest: FOLLOW_UP_REGISTRY_SCHEMA_DIGEST, sourceRevision: PRIOR, actionDigest: ACTION_DIGEST, handlerDigest: bundle('control'), epoch: id('epoch'), generation: 1, issuerReleaseDigest: bundle('issuer'), policyVersion: 'follow-up-retention-policy.v1' };
  const body = { version: VERSION, transport: 'private_service_binding_rpc', scope, origin: { sourceId: id('origin'), sequence: 1, originalAt: at - 1000, approvedAt: at, dispatchUntil: at + 240000 }, aliasSetDigest: hash('aliases'), replayHorizonUntil: at + 10 * day, retentionUntil: at + day - 2000, parentDeadline: at + day, deletionDeadline: null, issuedAt: at, expiresAt: at + 3600000, issuerSequence: 1, principals: ['owner', 'operator', 'reader'].map(role => ({ callerId: id(`caller/${role}`), keyId: id(role), publicKeySha256: fingerprint(role), role, notBefore: at, expiresAt: at + 3600000 })), signers: Object.fromEntries(roles.slice(4).map(r => [r, { keyId: id(r), publicKeySha256: fingerprint(r) }])) };
  const callerConfig = { REHEARSAL_MANIFEST: encode({ body, keyId: id('root'), signature: sign(null, manifestSigningBytes(body), keys.root.privateKey).toString('base64') }), REHEARSAL_CALLER_KEYS: encode({ root: { keyId: id('root'), publicKey: pub('root') }, principals: Object.fromEntries(['owner', 'operator', 'reader'].map(r => [r, pub(r)])) }) };
  const publicConfig = { ...callerConfig, OPERATOR_ACCESS_CONFIG: encode({ version: 'follow-up-operator-access.v1', origin: 'https://rehearsal.amarimethod.com', issuer: 'https://synthetic.cloudflareaccess.com', audience: hash('aud'), manifestDigest: hash(manifestSigningBytes(body)), scopeDigest: hash(canonical(scope)), issuedAt: at, expiresAt: at + 3600000, jwks: [{ kid: 'test', kty: 'RSA', alg: 'RS256', use: 'sig', n: rsa.n, e: rsa.e }], principals: [{ commonName: 'f'.repeat(32) + '.access', callerId: id('caller/operator'), keyId: id('operator'), role: 'operator' }] }) };
  const budget = { aggregateCeilingCents: 1000, remainingCents: 900, deploymentEstimateCents: 100, cleanupReserveCents: 100 };
  const prior = { version: 'follow-up-rehearsal-deployment-approval.v1', releaseId: hash('prior release'), issuedAt: at, expiresAt: at + 300000, reviewedRevision: PRIOR, sourceArtifactDigest: hash('prior reviewed deployment artifact'), accountId: TARGET.accountId, creates: { scripts: ['issuer', 'control', 'caller'].map(r => TARGET[r]), sqliteNamespace: { script: TARGET.control, className: 'FollowUpRehearsalRegistryV1', migrationTag: 'rehearsal-v1' } }, bucket: { name: TARGET.bucket, jurisdiction: 'us', creationDate: '2026-08-28T00:00:00Z', mode: 'existing-dedicated-empty' }, secretDigests: { issuer: hash('issuer secrets'), control: hash('control secrets'), caller: hash(canonical(callerConfig)) }, limits: DEPLOY_LIMITS, budget, acknowledgements: { temporaryPublic404Shell: true, createsThreeScriptsAndOneNamespace: true, noInvocation: true, noCleanupOrRollback: true, meteredUsage: true, exclusiveReleaseCustody: true } };
  const approval = { version: 'follow-up-rehearsal-gateway-approval.v1', releaseId: hash('gateway release'), issuedAt: at, expiresAt: at + 299000, reviewedRevision: REV, sourceArtifactDigest: candidate.artifactDigest, accountId: TARGET.accountId, creates: { scripts: [GATEWAY_TARGET] }, caller: { versionId: uuid(99), deploymentApproval: prior }, publicConfig, limits: GATEWAY_LIMITS, budget, acknowledgements: { temporaryPublic404Shell: true, createsOneScriptOnly: true, publicConfigurationOnly: true, noHostnameAttachment: true, noInvocation: true, noCleanupOrRollback: true, meteredUsage: true, exclusiveReleaseCustody: true } };
  const callerMeta = { main_module: 'worker.mjs', compatibility_date: '2026-08-27', compatibility_flags: ['nodejs_compat'], cache_options: { enabled: false }, limits: { cpu_ms: 1000, subrequests: 1 }, observability: { enabled: false }, logpush: false, tail_consumers: [], bindings: [{ name: 'REHEARSAL_MANIFEST', type: 'secret_text' }, { name: 'REHEARSAL_CALLER_KEYS', type: 'secret_text' }, { name: 'CONTROL', type: 'service', service: TARGET.control, entrypoint: 'FollowUpRehearsalControl' }], annotations: { 'workers/tag': `rehearsal-${prior.releaseId.slice(0, 16)}-final`, 'workers/message': `git_sha=${PRIOR};artifact_sha256=${prior.sourceArtifactDigest};bundle_sha256=${bundle('caller')};approval_sha256=${deploymentApprovalDigest(prior)}` } };
  const state = { calls: [], writes: [], consumed: 0, tokens: 0, workers: { [TARGET.caller]: { meta: callerMeta, content: callerBytes, versionId: uuid(99), private: true } } }, options = {};
  const json = (result, result_info) => Response.json({ success: true, errors: [], result, ...(result_info ? { result_info } : {}) });
  const list = array => json(array, { total_pages: 1, total_count: array.length });
  const fetch = async (url, init) => {
    const u = new URL(url), path = u.pathname.replace('/client/v4', ''), method = init.method; state.calls.push({ path, method });
    expect(u.origin).toBe('https://api.cloudflare.com'); expect(init.redirect).toBe('error'); expect(init.headers.Authorization).toBe('Bearer synthetic-test-only-token-123');
    if (options.throwRead) throw Error('sensitive provider failure');
    if (path === '/zones') return options.incompleteZones ? json([], { total_pages: 2, total_count: 51 }) : options.tooManyZones ? list(Array.from({ length: 9 }, () => ({ id: ZONE, account: { id: TARGET.accountId } }))) : list([{ id: ZONE, account: { id: TARGET.accountId } }]);
    if (path === `/zones/${ZONE}/workers/routes`) return json(options.route ? [{ script: GATEWAY_TARGET }] : [], options.incompleteRoutes ? { total_pages: 2 } : undefined);
    const base = `/accounts/${TARGET.accountId}`;
    if (path === `${base}/workers/domains`) return list(options.domain ? [{ service: TARGET.caller }] : []);
    const match = path.match(/\/workers\/scripts\/([^/]+)(.*)$/); if (!match) throw Error('unexpected synthetic path');
    const [, name, suffix] = match; expect([GATEWAY_TARGET, TARGET.caller]).toContain(name); let worker = state.workers[name]; const target = name === GATEWAY_TARGET;
    if (method === 'PUT') {
      expect(target).toBe(true); expect(suffix).toBe(''); const form = await new Response(init.body, { headers: { 'Content-Type': init.headers['Content-Type'] } }).formData();
      expect([...form.keys()]).toEqual(['metadata', 'worker.mjs']); const meta = JSON.parse(form.get('metadata')), content = Buffer.from(await form.get('worker.mjs').arrayBuffer());
      worker = { meta, content, versionId: uuid(state.writes.length + 1), private: worker?.private ?? false }; state.workers[name] = worker; state.writes.push({ method, meta, content });
      if (options.lostPut || (options.lostFinal && state.writes.length === 3)) throw Error('sensitive upstream failure'); return json({ id: name });
    }
    if (suffix === '/settings' && !worker) return options.existingGateway ? json({ bindings: [] }) : Response.json({ success: false }, { status: 404 });
    if (!worker) throw Error('synthetic absent caller');
    if (suffix === '/subdomain') { if (method === 'POST') { expect(target).toBe(true); expect(JSON.parse(init.body)).toEqual({ enabled: false, previews_enabled: false }); worker.private = !options.stillPublic; state.writes.push({ method }); if (options.lostDisable) throw Error('unknown disable outcome'); } return json({ enabled: !worker.private, previews_enabled: !worker.private }); }
    if (suffix === '/deployments') return json({ deployments: [{ id: uuid(100), versions: [{ version_id: worker.versionId, percentage: options.splitCaller && !target ? 50 : 100 }] }] });
    if (suffix.startsWith('/versions/')) return json({ id: worker.versionId, annotations: options.badCallerProvenance && !target ? {} : options.badGatewayProvenance && target ? {} : { ...worker.meta.annotations, 'workers/triggered_by': 'upload' } });
    if (suffix === '/content/v2') { const form = new FormData(); form.set('worker.mjs', new Blob([(options.corruptCaller && !target) || (options.corruptGateway && target) ? 'corrupt' : worker.content]), 'worker.mjs'); if (options.extraModule && target) form.set('extra.mjs', new Blob(['extra']), 'extra.mjs'); return new Response(form, { headers: { 'cf-entrypoint': options.wrongEntrypoint ? 'wrong.mjs' : 'worker.mjs' } }); }
    if (suffix === '/settings') { const meta = structuredClone(worker.meta); if (options.extraBinding && target) meta.bindings.push({ name: 'UNAPPROVED', type: 'plain_text', text: 'no' }); if (options.badCallerBinding && !target) meta.bindings[2].service = 'production'; if (options.alteredPublicConfig && target && meta.bindings.length) meta.bindings[0].text += ' '; return json(meta); }
    if (suffix === '/schedules') return json({ schedules: options.schedule ? [{ cron: '* * * * *' }] : [] });
    throw Error('unexpected synthetic operation');
  };
  const args = { execute: true, approval, approvedDigest: gatewayDeploymentApprovalDigest(approval), git, fetch, consumeRelease: async q => { state.consumed++; return { status: 'consumed', releaseId: q.releaseId, approvalDigest: q.approvalDigest }; }, withCloudflareToken: async use => { state.tokens++; return use('synthetic-test-only-token-123'); } };
  return { args, approval, state, options, refresh() { args.approvedDigest = gatewayDeploymentApprovalDigest(approval); } };
}

describe('guarded private gateway installation: real source with synthetic providers', () => {
  it('pins the true operator graph and tools; inspection never authorizes deployment', () => { expect(candidate.deploymentAuthorized).toBe(false); expect(candidate.artifact.files.map(f => f.path)).toEqual(expect.arrayContaining(['scripts/follow-up-rehearsal-gateway-deploy.mjs', 'follow-up-rehearsal-worker/src/operator-access.mjs', 'follow-up-rehearsal-worker/wrangler.operator.jsonc'])); expect(candidate.artifact.tools.files).toHaveLength(4); expect(candidate.artifact.bundles.map(b => b.role)).toEqual(['issuer', 'control', 'caller', 'gateway']); });
  it('uploads exactly shell/disable/final and reads real bytes without attaching hostname or invoking', async () => {
    const f = fixture(), result = await deployGatewayRehearsal(f.args); expect(result).toMatchObject({ status: 'deployed-private-not-invoked', attemptedWrites: 3, consumptionState: 'consumed', runtimeInvoked: false, hostnameAttached: false });
    expect(f.state.writes.map(w => w.method)).toEqual(['PUT', 'POST', 'PUT']); expect(f.state.writes[0].meta.bindings).toEqual([]); expect(f.state.writes[0].content.toString()).toBe(SHELL_SOURCE);
    expect(f.state.writes[2].meta.bindings.map(b => b.type).sort()).toEqual(['plain_text', 'plain_text', 'plain_text', 'service']); expect(hash(f.state.writes[2].content)).toBe(candidate.artifact.bundles.find(b => b.role === 'gateway').sha256);
    expect(result.identity.phase).toBe('final'); expect(result.requests).toBeLessThanOrEqual(GATEWAY_LIMITS.requests); expect(JSON.stringify(result)).not.toMatch(/PRIVATE KEY|synthetic-test-only-token|sensitive/);
  });
  it.each(['existingGateway', 'incompleteZones', 'tooManyZones', 'incompleteRoutes', 'route', 'domain', 'corruptCaller', 'badCallerProvenance', 'badCallerBinding', 'splitCaller', 'schedule', 'throwRead', 'wrongEntrypoint'])('refuses %s before gateway writes', async failure => { const f = fixture(); f.options[failure] = true; expect(await deployGatewayRehearsal(f.args)).toMatchObject({ status: 'refused', attemptedWrites: 0 }); expect(f.state.writes).toEqual([]); });
  it.each(['lostPut', 'lostDisable', 'corruptGateway', 'badGatewayProvenance', 'extraModule', 'extraBinding', 'stillPublic'])('stops after %s without final activation/retry', async failure => { const f = fixture(); f.options[failure] = true; const r = await deployGatewayRehearsal(f.args); expect(r.status).toBe('reconciliation-required'); expect(r.attemptedWrites).toBeLessThanOrEqual(2); expect(r.retryAllowed).toBe(false); });
  it.each(['lostFinal', 'alteredPublicConfig'])('stops on %s final upload/readback without retry', async failure => { const f = fixture(); f.options[failure] = true; expect(await deployGatewayRehearsal(f.args)).toMatchObject({ status: 'reconciliation-required', attemptedWrites: 3, retryAllowed: false }); });
  it.each(['dirty', 'stale-main', 'wrong-origin', 'hidden-source'])('refuses %s before consumption', async kind => { const f = fixture(); f.args.git = a => kind === 'dirty' && a[0] === 'status' ? ' M source' : kind === 'stale-main' && a[0] === 'ls-remote' ? `${PRIOR}\trefs/heads/main` : kind === 'wrong-origin' && a[0] === 'remote' ? 'https://example.com' : kind === 'hidden-source' && a[0] === 'show' ? 'different' : git(a); expect(await deployGatewayRehearsal(f.args)).toMatchObject({ status: 'refused', requests: 0 }); expect(f.state.consumed).toBe(0); });
  it('rechecks main before every write', async () => { const f = fixture(); let reads = 0; f.args.git = a => a[0] === 'ls-remote' && ++reads > 2 ? `${PRIOR}\trefs/heads/main` : git(a); expect(await deployGatewayRehearsal(f.args)).toMatchObject({ status: 'reconciliation-required', attemptedWrites: 1 }); });
  it('rejects a concurrent shell replacement rather than overwrite it', async () => { const f = fixture(), fetcher = f.args.fetch; f.args.fetch = async (url, init) => { if (f.state.writes.length === 2) f.state.workers[GATEWAY_TARGET].versionId = uuid(123); return fetcher(url, init); }; expect(await deployGatewayRehearsal(f.args)).toMatchObject({ status: 'reconciliation-required', attemptedWrites: 2 }); });
  it('rejects changed caller bytes after shell and before final upload', async () => { const f = fixture(), fetcher = f.args.fetch; f.args.fetch = async (url, init) => { if (f.state.writes.length === 2) f.options.corruptCaller = true; return fetcher(url, init); }; expect(await deployGatewayRehearsal(f.args)).toMatchObject({ status: 'reconciliation-required', attemptedWrites: 2 }); });
  it('refuses the wrong pinned caller version before writes', async () => { const f = fixture(); f.approval.caller.versionId = uuid(77); f.refresh(); expect(await deployGatewayRehearsal(f.args)).toMatchObject({ status: 'refused', attemptedWrites: 0 }); });
  it('refuses a public caller before writes', async () => { const f = fixture(); f.state.workers[TARGET.caller].private = false; expect(await deployGatewayRehearsal(f.args)).toMatchObject({ status: 'refused', attemptedWrites: 0 }); });
  it('reports reconciliation when caller drifts after final upload', async () => { const f = fixture(), fetcher = f.args.fetch; f.args.fetch = async (url, init) => { if (f.state.writes.length === 3) f.state.workers[TARGET.caller].versionId = uuid(123); return fetcher(url, init); }; expect(await deployGatewayRehearsal(f.args)).toMatchObject({ status: 'reconciliation-required', attemptedWrites: 3 }); });
  it('never overwrites a completed install on a second attempt', async () => { const f = fixture(); expect((await deployGatewayRehearsal(f.args)).status).toBe('deployed-private-not-invoked'); const before = f.state.writes.length; f.args.consumeRelease = async () => ({ status: 'already-consumed' }); expect(await deployGatewayRehearsal(f.args)).toMatchObject({ status: 'reconciliation-required', requests: 0, attemptedWrites: 0, retryAllowed: false }); expect(f.state.writes).toHaveLength(before); });
  it('refuses no explicit execute before all external callbacks', async () => { const f = fixture(); f.args.execute = false; expect(await deployGatewayRehearsal(f.args)).toMatchObject({ status: 'refused', requests: 0 }); expect(f.state.consumed).toBe(0); });
  it.each(['lost', 'wrong', 'already'])('no provider calls after %s durable acknowledgement', async kind => { const f = fixture(); f.args.consumeRelease = async q => { if (kind === 'lost') throw Error('unknown'); return kind === 'wrong' ? { status: 'consumed', releaseId: q.releaseId, approvalDigest: hash('wrong') } : { status: 'already-consumed' }; }; expect(await deployGatewayRehearsal(f.args)).toMatchObject({ status: 'reconciliation-required', consumptionState: 'unknown', requests: 0, attemptedWrites: 0 }); expect(f.state.tokens).toBe(0); });
  it('ignores caller mutation of approval after asynchronous consumption', async () => { const f = fixture(), consume = f.args.consumeRelease; f.args.consumeRelease = async q => { const r = await consume(q); f.approval.publicConfig = {}; f.approval.creates.scripts.push('production'); return r; }; expect((await deployGatewayRehearsal(f.args)).status).toBe('deployed-private-not-invoked'); });
  it('does not accept a late unawaited credential callback', async () => { const f = fixture(); let late; f.args.withCloudflareToken = async use => { late = use; }; expect(await deployGatewayRehearsal(f.args)).toMatchObject({ status: 'refused', attemptedWrites: 0 }); await expect(late('synthetic-test-only-token-123')).rejects.toThrow(); expect(f.state.calls).toEqual([]); });
  it('observes a started but unawaited credential callback rejection', async () => { const f = fixture(); let finished; const settled = new Promise(r => { finished = r; }); f.args.withCloudflareToken = use => { void use('synthetic-test-only-token-123').finally(finished).catch(() => {}); }; expect((await deployGatewayRehearsal(f.args)).status).toBe('refused'); await settled; expect(f.state.writes).toEqual([]); });
  it('bounds an oversized provider response', async () => { const f = fixture(); f.args.fetch = async () => new Response('x'.repeat(GATEWAY_LIMITS.responseBytes + 1)); expect(await deployGatewayRehearsal(f.args)).toMatchObject({ status: 'refused', attemptedWrites: 0, requests: 1 }); });
  it('closes a hung consume window with unknown state and no later credential use', async () => {
    vi.useFakeTimers({ toFake: ['Date', 'setTimeout', 'clearTimeout'] }); const f = fixture(); let began, release; const started = new Promise(r => { began = r; }), held = new Promise(r => { release = r; });
    try { f.args.consumeRelease = async q => { began(); await held; return { status: 'consumed', releaseId: q.releaseId, approvalDigest: q.approvalDigest }; }; const running = deployGatewayRehearsal(f.args);
      await Promise.race([started, running.then(r => { throw Error(`consume never started: ${JSON.stringify(r)}`); })]); await vi.advanceTimersByTimeAsync(GATEWAY_LIMITS.operationMs + 1); expect(await running).toMatchObject({ status: 'reconciliation-required', consumptionState: 'unknown', requests: 0 }); release(); await Promise.resolve(); await Promise.resolve(); expect(f.state.tokens).toBe(0);
    } finally { release(); vi.useRealTimers(); }
  });
  it('bounds a hung provider read and prevents late continuation after timeout', async () => {
    vi.useFakeTimers({ toFake: ['Date', 'setTimeout', 'clearTimeout'] }); const f = fixture(); let began, release; const started = new Promise(r => { began = r; }), held = new Promise(r => { release = r; }); let calls = 0;
    try { f.args.fetch = async () => { calls++; began(); await held; return Response.json({ success: true, result: [], result_info: { total_count: 0, total_pages: 0 } }); }; const running = deployGatewayRehearsal(f.args);
      await Promise.race([started, running.then(r => { throw Error(`provider never started: ${JSON.stringify(r)}`); })]); await vi.advanceTimersByTimeAsync(GATEWAY_LIMITS.timeoutMs + 1); expect(await running).toMatchObject({ status: 'refused', attemptedWrites: 0, requests: 1 }); release(); await Promise.resolve(); await Promise.resolve(); expect(calls).toBe(1);
    } finally { release(); vi.useRealTimers(); }
  });
  for (const [name, mutate] of [
    ['production name', a => { a.creates.scripts = ['production']; }], ['private material', a => { a.publicConfig.REHEARSAL_KEYS = 'private'; }], ['wrong prior caller config', a => { a.caller.deploymentApproval.secretDigests.caller = hash('wrong'); }], ['same consumption ID', a => { a.caller.deploymentApproval.releaseId = a.releaseId; }], ['expired caller approval', a => { a.caller.deploymentApproval.expiresAt = Date.now() - 1; }], ['over budget', a => { a.budget.aggregateCeilingCents = 1001; }], ['unbounded writes', a => { a.limits = { ...a.limits, writes: 4 }; }], ['hostname authority', a => { a.acknowledgements.noHostnameAttachment = false; }],
  ]) it(`rejects ${name} approval before custody`, async () => { const f = fixture(); mutate(f.approval); f.refresh(); expect(() => validateGatewayDeploymentApproval(f.approval, f.args.approvedDigest)).toThrow(); expect(await deployGatewayRehearsal(f.args)).toMatchObject({ status: 'refused', requests: 0 }); expect(f.state.consumed).toBe(0); });
  it('genuine host default gateway transport consumes governed tag before exact Cloudflare custody', async () => {
    const f = fixture(), hostCandidate = await inspectHostCandidate({ git }), owner = { keyId: 'host-owner', publicKey: pub('root') }, at = f.approval.issuedAt;
    const values = { github: 'synthetic-github-token-at-least-20', cloudflare: 'synthetic-test-only-token-123' }, gets = [], ledgerCalls = []; let tag, ref;
    const policy = { version: 'follow-up-rehearsal-host-approval.v1', mode: 'deploy-gateway', releaseId: f.approval.releaseId, issuedAt: at, expiresAt: f.approval.expiresAt, reviewedRevision: REV, hostArtifactDigest: hostCandidate.artifactDigest, ownerKeyId: owner.keyId,
      custody: { executable: '/synthetic/bws', executableSha256: hash('synthetic binary'), records: Object.fromEntries(['github', 'cloudflare'].map((role, i) => [role, { id: uuid(i + 1), key: HOST_RECORD_KEYS[role], projectId: uuid(10), organizationId: uuid(11), revisionDate: '2026-08-28T00:00:00Z', sha256: hash(values[role]) }])) },
      ledger: { repository: 'Eben283/amarimethod-website', refPrefix: 'refs/tags/followup-rehearsal-consumed/', rulesetId: 21768018 }, operation: { approvalDigest: f.args.approvedDigest } };
    const fetcher = async (url, init) => { if (!url.startsWith('https://api.github.com')) { expect(gets).toEqual(['github', 'cloudflare']); expect(ledgerCalls.filter(c => c.method === 'POST')).toHaveLength(2); return f.args.fetch(url, init); }
      const path = new URL(url).pathname.split('/amarimethod-website')[1], method = init.method; ledgerCalls.push({ path, method });
      if (path.startsWith('/rulesets/')) return Response.json({ id: 21768018, source_type: 'Repository', source: 'Eben283/amarimethod-website', target: 'tag', enforcement: 'active', bypass_actors: [], conditions: { ref_name: { include: ['refs/tags/followup-rehearsal-consumed/*'], exclude: [] } }, rules: [{ type: 'update' }, { type: 'deletion' }] });
      if (path === '/git/ref/heads/main') return Response.json({ object: { type: 'commit', sha: REV } });
      if (path === '/git/tags' && method === 'POST') { const b = JSON.parse(init.body); tag = { sha: 'c'.repeat(40), tag: b.tag, message: b.message, object: { sha: b.object, type: b.type } }; return Response.json(tag, { status: 201 }); }
      if (path === '/git/refs' && method === 'POST') { const b = JSON.parse(init.body); ref = { ref: b.ref, object: { sha: b.sha, type: 'tag' } }; return Response.json(ref, { status: 201 }); }
      if (path.startsWith('/git/ref/tags/')) return Response.json(ref ?? {}, { status: ref ? 200 : 404 });
      if (path === '/git/tags/' + 'c'.repeat(40)) return Response.json(tag); throw Error('unexpected synthetic GitHub path');
    };
    const result = await runRehearsalHost({ execute: true, hostApproval: { policy, signature: sign(null, hostApprovalSigningBytes(policy), keys.root.privateKey).toString('base64url') }, trustedRoot: owner, gatewayApproval: f.approval, git, fetch: fetcher, runBws: async ({ record }) => { const role = Object.keys(policy.custody.records).find(r => policy.custody.records[r].id === record.id); gets.push(role); return { ...record, value: values[role] }; } });
    expect(result).toMatchObject({ status: 'deployed-private-not-invoked', consumptionState: 'consumed', githubWrites: 2, deployment: { attemptedWrites: 3, hostnameAttached: false } }); expect(gets).toEqual(['github', 'cloudflare']);
  });
});
