import { OPS_SURFACE_NAV_CSS, opsEmbedBootScript, opsSurfaceNavHtml } from "../../functions/lib/ops-surface-nav.js";

const CLIENT_DESK_HTML = `<!doctype html>
<html lang="en"><head>
<meta charset="utf-8" /><meta name="viewport" content="width=device-width, initial-scale=1" />
<meta name="robots" content="noindex, nofollow" /><title>Amari Client Desk</title>
<style>
  :root { color-scheme: light; font-family: "DM Sans", ui-sans-serif, system-ui, sans-serif; background: #f7f8f7; color: #223e48; }
  * { box-sizing: border-box; } body { margin: 0; min-height: 100vh; background: #f7f8f7; } main { width: min(1160px, calc(100% - 32px)); margin: auto; padding: 42px 0 72px; }
  .eyebrow { color: #637b83; font-size: .72rem; font-weight: 800; letter-spacing: .15em; text-transform: uppercase; } h1 { max-width: 720px; margin: 9px 0 10px; font-family: "Bona Nova", Georgia, serif; font-size: clamp(2.5rem, 6vw, 4.7rem); font-weight: 400; letter-spacing: -.055em; line-height: .96; }
  .lede { max-width: 680px; margin: 0; color: #647980; line-height: 1.55; } .notice { margin: 20px 0 28px; color: #788a90; font-size: .83rem; }
  .tools { display: flex; flex-wrap: wrap; align-items: center; gap: 10px; margin: 28px 0 18px; } input, select { min-height: 44px; border: 1px solid #cfdbdc; border-radius: 10px; background: #fff; color: #223e48; font: inherit; } input { flex: 1 1 300px; padding: 10px 13px; } select { padding: 9px 10px; } input:focus, select:focus, button:focus { outline: 2px solid #e5846c; outline-offset: 2px; }
  .status { margin-left: auto; color: #72858b; font-size: .8rem; } .layout { display: grid; grid-template-columns: minmax(0, 1.1fr) minmax(330px, .9fr); gap: 16px; } .shell { overflow: hidden; border: 1px solid #d7e1e1; border-radius: 16px; background: #fff; box-shadow: 0 12px 30px rgba(35, 62, 72, .07); } .list-head { display: flex; align-items: baseline; justify-content: space-between; gap: 12px; padding: 17px 16px 12px; border-bottom: 1px solid #edf1f0; } .list-head h2 { margin: 0; font-family: "Bona Nova", Georgia, serif; font-size: 1.35rem; font-weight: 400; } .list-head span { color: #e07058; font-size: .75rem; font-weight: 750; }
  .list { margin: 0; padding: 0; list-style: none; } .row { width: 100%; display: grid; grid-template-columns: 10px minmax(0, 1fr) auto; gap: 12px; align-items: start; padding: 15px; border: 0; border-bottom: 1px solid #edf1f0; background: transparent; color: inherit; cursor: pointer; font: inherit; text-align: left; } .row:hover, .row:focus-visible { background: #f6faf8; }
  .signal { width: 8px; height: 8px; margin-top: 7px; border-radius: 50%; background: #a8b8bb; } .signal.inbound { background: #e5846c; box-shadow: 0 0 0 4px rgba(229,132,108,.14); } .name { display: block; font-size: .94rem; font-weight: 750; } .preview { display: -webkit-box; overflow: hidden; margin-top: 4px; color: #647980; font-size: .81rem; line-height: 1.4; -webkit-box-orient: vertical; -webkit-line-clamp: 2; }
  .meta { max-width: 145px; color: #72858b; font-size: .72rem; line-height: 1.45; text-align: right; } .empty { padding: 32px 18px; color: #72858b; line-height: 1.5; } .profile { min-height: 500px; padding: 24px; } .profile h2 { margin: 0; font-family: "Bona Nova", Georgia, serif; font-size: 1.8rem; font-weight: 400; letter-spacing: -.03em; } .profile p { color: #647980; line-height: 1.5; }
  .facts { display: flex; flex-wrap: wrap; gap: 7px; margin: 18px 0 24px; } .fact { padding: 6px 8px; border-radius: 999px; background: #eef4f2; color: #46636b; font-size: .73rem; } .section { margin-top: 24px; } .section h3 { margin: 0 0 9px; color: #647980; font-size: .77rem; letter-spacing: .08em; text-transform: uppercase; } .timeline { display: grid; gap: 9px; } .event { padding: 10px; border-left: 2px solid #8da8a0; background: #f6f9f7; } .event.inbound { border-color: #e5846c; } .event strong, .event span { display: block; } .event strong { color: #294852; font-size: .78rem; } .event span { margin-top: 3px; color: #647980; font-size: .75rem; line-height: 1.4; } .quiet { color: #72858b; font-size: .83rem; }
  @media (max-width: 760px) { main { padding-top: 32px; } .layout { grid-template-columns: 1fr; } .profile { min-height: 0; } .status { width: 100%; margin-left: 0; } }
  /*__OPS_SURFACE_NAV_CSS__*/
</style></head><body><script>__OPS_EMBED_BOOT__</script><main>__OPS_SURFACE_NAV__
<div class="eyebrow">Read-only client workspace</div><h1>Client Desk</h1><p class="lede">A calm view of every client relationship: the last real communication, who has replied, and the context needed before you open GoHighLevel.</p>
<p class="notice">The desk never sends, books, or edits records. GoHighLevel remains the source and sender.</p>
<div class="tools"><input id="query" type="search" autocomplete="off" placeholder="Search name, email, or phone" aria-label="Search clients" /><select id="scope" aria-label="Directory scope"><option value="clients">Client records</option><option value="all">All mirrored contacts</option></select><span class="status" id="status">Loading client records…</span></div>
<div class="layout"><section class="shell" aria-label="Client list"><header class="list-head"><h2>Client relationships</h2><span id="reply-count">Checking replies…</span></header><ul class="list" id="list"></ul></section><aside class="shell profile" id="profile"><h2>Select a client</h2><p>Choose a client to see their latest communication and read-only relationship history.</p></aside></div>
</main><script>
(() => { const list = document.getElementById('list'), profile = document.getElementById('profile'), query = document.getElementById('query'), scope = document.getElementById('scope'), status = document.getElementById('status'), replyCount = document.getElementById('reply-count'); let timer, selected = null;
 const ago = (value) => { if (!value) return 'No communication mirrored'; const days = Math.floor((Date.now() - new Date(value).getTime()) / 86400000); return days <= 0 ? 'Today' : days === 1 ? 'Yesterday' : days + 'd ago'; };
 const label = (row) => row.last_direction === 'inbound' ? 'Client replied' : row.last_direction === 'outbound' ? 'Last sent' : 'No communication';
 const escape = (value) => String(value || '').replace(/[&<>"']/g, (c) => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c]);
 async function load() { const params = new URLSearchParams({ limit: '50', scope: scope.value }); if (query.value.trim().length >= 2) params.set('query', query.value.trim()); status.textContent = 'Loading…'; const res = await fetch('/client-desk/contacts?' + params, { credentials: 'same-origin' }); if (!res.ok) { status.textContent = 'Client list unavailable.'; replyCount.textContent = 'Could not load replies'; return; } const payload = await res.json(); const replies = payload.contacts.filter((row) => row.last_direction === 'inbound').length; list.replaceChildren(); status.textContent = payload.contacts.length + ' record' + (payload.contacts.length === 1 ? '' : 's') + (scope.value === 'clients' ? ' with activity' : ''); replyCount.textContent = replies ? replies + ' need a reply' : 'No replies waiting'; if (!payload.contacts.length) { list.innerHTML = '<li class="empty">No matching client records.</li>'; return; } for (const row of payload.contacts) { const item = document.createElement('li'); const button = document.createElement('button'); button.className = 'row'; button.innerHTML = '<i class="signal ' + (row.last_direction === 'inbound' ? 'inbound' : '') + '"></i><span><strong class="name">' + escape(row.display_name || 'Unnamed client') + '</strong><span class="preview">' + escape(row.last_preview || 'No communication has been mirrored for this client.') + '</span></span><span class="meta">' + label(row) + '<br>' + ago(row.last_occurred_at) + (row.next_appointment_at ? '<br>Next: ' + escape(new Date(row.next_appointment_at).toLocaleDateString(undefined, { month: 'short', day: 'numeric' })) : '') + '</span>'; button.addEventListener('click', () => show(row.id)); item.append(button); list.append(item); } }
 async function show(id) { selected = id; profile.innerHTML = '<p class="quiet">Loading client record…</p>'; const res = await fetch('/client-desk/contacts/' + encodeURIComponent(id) + '?limit=12', { credentials: 'same-origin' }); if (!res.ok) { profile.innerHTML = '<p class="quiet">This client record could not be loaded.</p>'; return; } const data = await res.json(), c = data.contact; const communications = data.communications || []; const messages = communications.length ? communications.map((m) => '<div class="event ' + (m.direction === 'inbound' ? 'inbound' : '') + '"><strong>' + (m.direction === 'inbound' ? 'Client' : 'Sent') + ' · ' + escape(m.channel || 'message') + ' · ' + escape(ago(m.occurred_at)) + '</strong><span>' + escape(m.subject_or_preview || 'No preview available') + '</span></div>').join('') : '<p class="quiet">No communication has been mirrored for this client.</p>'; const facts = [c.email_normalized, c.phone_e164, data.importedCurrentState?.series_type, data.importedCurrentState?.sessions_remaining != null ? data.importedCurrentState.sessions_remaining + ' sessions remaining' : null, data.nextAppointment ? 'Next appointment ' + new Date(data.nextAppointment.starts_at).toLocaleDateString(undefined, { month: 'short', day: 'numeric' }) : null].filter(Boolean).map((v) => '<span class="fact">' + escape(v) + '</span>').join(''); profile.innerHTML = '<h2>' + escape(c.display_name || 'Unnamed client') + '</h2><div class="facts">' + (facts || '<span class="fact">Imported client record</span>') + '</div><section class="section"><h3>Communication</h3><div class="timeline">' + messages + '</div></section><section class="section"><h3>Appointments</h3><div class="timeline">' + ((data.appointments || []).slice(0, 4).map((a) => '<div class="event"><strong>' + escape(new Date(a.starts_at).toLocaleDateString(undefined, { month: 'short', day: 'numeric' })) + ' · ' + escape(a.status || 'recorded') + '</strong><span>' + escape(a.service_name || 'Service not mapped') + '</span></div>').join('') || '<p class="quiet">No appointments mirrored.</p>') + '</div></section>'; }
 query.addEventListener('input', () => { clearTimeout(timer); timer = setTimeout(load, 220); }); scope.addEventListener('change', load); load(); })();
</script></body></html>`;

export function clientDeskHtml() { return CLIENT_DESK_HTML.replaceAll("__OPS_SURFACE_NAV__", opsSurfaceNavHtml("Client Desk")).replaceAll("__OPS_SURFACE_NAV_CSS__", OPS_SURFACE_NAV_CSS).replaceAll("__OPS_EMBED_BOOT__", opsEmbedBootScript()); }
